export const SEGMENT_LABELS: Record<string, string> = {
  dashboard: "Início",
  leads: "Leads",
  contacts: "Contatos",
  companies: "Empresas",
  deals: "Negócios",
  tasks: "Tarefas",
  tickets: "Tickets",
  proposals: "Propostas",
  invoices: "Faturas",
  meetings: "Reuniões",
  notes: "Notas",
  inbox: "Caixa de entrada",
  chat: "Chat",
  email: "E-mail",
  whatsapp: "WhatsApp",
  communications: "Comunicações",
  campaigns: "Campanhas",
  prospecting: "Prospecção",
  analytics: "Analytics",
  reports: "Relatórios",
  dashboards: "Dashboards",
  settings: "Configurações",
  admin: "Admin",
  integrations: "Integrações",
  marketplace: "Marketplace",
  agents: "Agentes",
  sdr: "SDR",
  queues: "Filas",
  play: "Executar",
  "landing-pages": "Landing pages",
  "quote-templates": "Modelos de orçamento",
  "bug-reports": "Chamados internos",
  "my-bug-reports": "Meus chamados",
  "import-hubspot": "Importar HubSpot",
  "import-csv": "Importar CSV",
  workspaces: "Workspaces",
  alerts: "Alertas",
  quotas: "Cotas",
  sandbox: "Sandbox",
  status: "Status",
  // Settings sub-pages
  "access-policy": "Política de acesso",
  "ads-sync": "Sincronização de anúncios",
  "api-keys": "Chaves de API",
  "audit-export": "Exportar auditoria",
  "audit-log": "Log de auditoria",
  billing: "Cobrança",
  booking: "Agendamentos",
  branding: "Identidade visual",
  calendars: "Calendários",
  clauses: "Cláusulas",
  "custom-objects": "Objetos personalizados",
  "custom-properties": "Propriedades personalizadas",
  "data-residency": "Residência de dados",
  dunning: "Cobrança recorrente",
  "email-templates": "Modelos de e-mail",
  enrichment: "Enriquecimento",
  esign: "Assinatura eletrônica",
  exports: "Exportações",
  forms: "Formulários",
  goals: "Metas",
  "hubspot-sync": "Sincronização HubSpot",
  "hubspot-users": "Usuários HubSpot",
  kb: "Base de conhecimento",
  language: "Idioma",
  "lead-sources": "Origens de leads",
  macros: "Macros",
  mobile: "Mobile",
  nfse: "NFS-e",
  notifications: "Notificações",
  slack: "Slack",
  payments: "Pagamentos",
  pipelines: "Funis",
  playbooks: "Playbooks",
  portal: "Portal",
  "property-groups: ": "Grupos de propriedades",
  "property-groups": "Grupos de propriedades",
  "prospecting-scripts": "Scripts de prospecção",
  quotes: "Orçamentos",
  "record-layouts": "Layouts de registro",
  recurring: "Recorrências",
  roles: "Papéis e permissões",
  rotation: "Rotação",
  scim: "SCIM",
  scoring: "Lead scoring",
  security: "Segurança",
  segments: "Segmentos",
  sequences: "Sequências",
  sla: "SLA",
  sso: "SSO",
  subscriptions: "Assinaturas",
  surveys: "Pesquisas",
  teams: "Membros",
  "user-groups": "Times",
  video: "Vídeo",
  "voice-agent": "Agente de voz",
  "wa-ads": "Anúncios WhatsApp",
  webhooks: "Webhooks",
  "whatsapp-catalogs": "Catálogos WhatsApp",
  "whatsapp-templates": "Modelos WhatsApp",
  widget: "Widget",
  workflows: "Automações",
  "workspace-team": "Membros",
  zapier: "Zapier",
};

export function prettifySegment(seg: string): string {
  // ID-like (uuid or numeric) → Detalhes
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(seg))
    return "Detalhes";
  if (/^\d+$/.test(seg)) return "Detalhes";
  if (SEGMENT_LABELS[seg]) return SEGMENT_LABELS[seg];
  return seg
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}
