// Metadados de campos do catálogo de entidades: rótulos pt-BR, overrides por
// entidade e registro de aliases legados. Vive fora de `*.functions.ts` porque
// módulos de server function são divididos no build e perderiam constantes de
// runtime no bundle do cliente — e para permitir teste unitário direto.
import { CONTRACT_FIELD_LABELS } from "./contracts/workflow-field-meta";

// Rótulos amigáveis (pt-BR) — fallback é snake_case → Title Case.
export const LABELS: Record<string, string> = {
  first_name: "Nome",
  last_name: "Sobrenome",
  email: "Email",
  phone: "Telefone",
  mobile_phone: "Celular",
  company: "Empresa",
  company_name: "Empresa (texto livre)",
  company_id: "Empresa",
  source: "Origem",
  status: "Status",
  score: "Score",
  label: "Etiqueta",
  notes: "Notas",
  job_title: "Cargo",
  title: "Cargo",
  city: "Cidade",
  state: "UF",
  country: "País",
  cep: "CEP",
  address: "Endereço",
  website: "Site",
  domain: "Domínio",
  cnpj: "CNPJ",
  cnpj_enriched_at: "CNPJ enriquecido em",
  industry: "Setor",
  size: "Porte",
  annualrevenue: "Receita anual",
  is_target_account: "Target account",
  target_account_tier: "Tier de target",
  type: "Tipo",
  marketing_status: "Status de marketing",
  legal_basis: "Base legal",
  consent_date: "Data de consentimento",
  lifecyclestage: "Lifecycle stage",
  hs_lead_status: "Status (HubSpot)",
  linkedin_url: "LinkedIn",
  linkedin_company_page: "LinkedIn da empresa",
  twitter_handle: "Twitter",
  twitterhandle: "Twitter",
  facebook_company_page: "Facebook da empresa",
  portal_enabled: "Portal habilitado",
  assigned_user_id: "Responsável (legado)",
  pipeline_id: "Pipeline",
  stage: "Etapa",
  stage_id: "Etapa (ID)",
  name: "Nome",
  value: "Valor",
  currency: "Moeda",
  expected_close_date: "Fechamento esperado",
  lost_at: "Perdido em",

  dealtype: "Tipo de negócio",
  hs_priority: "Prioridade",
  hs_deal_stage_probability: "Probabilidade",
  closed_lost_reason: "Motivo de perda",
  closed_won_reason: "Motivo de ganho",
  num_associated_contacts: "Nº contatos associados",
  primary_contact_id: "Contato principal",
  parent_company_id: "Empresa-mãe",
  hubspot_owner_id_text: "Responsável (HubSpot)",
  hs_lead_source_detail: "Detalhe da origem",
  description: "Descrição",
  timezone: "Fuso horário",
  created_at: "Criado em",
  updated_at: "Atualizado em",
  // Tickets
  subject: "Assunto",
  priority: "Prioridade",
  assignee_id: "Responsável",
  due_at: "Vence em",
  sla_policy_id: "Política de SLA",
  first_response_at: "Primeira resposta em",
  resolved_at: "Resolvido em",
  closed_at: "Fechado em",
  reopened_at: "Reaberto em",
  contact_id: "Contato",
  deal_id: "Negócio",
  tags: "Tags",
  channel: "Canal",
  category: "Categoria",
  subcategory: "Subcategoria",
  resolution: "Resolução",
  satisfaction_score: "Nota de satisfação",
  ticket_number: "Número do chamado",
  sla_response_due_at: "SLA de resposta até",
  sla_resolution_due_at: "SLA de resolução até",
  sla_breached: "SLA violado",
  csat_rating: "Avaliação CSAT",
  csat_comment: "Comentário CSAT",
  kb_article_ids: "Artigos KB vinculados",
  is_public: "Público",
  external_id: "ID externo",
  form_id: "Formulário",
  // Atividades / tarefas
  body: "Descrição",
  activity_type: "Tipo de atividade",
  due_date: "Vence em",
  completed_at: "Concluída em",
  // Projects / tasks / milestones
  project_id: "Projeto",
  milestone_id: "Marco",
  parent_task_id: "Tarefa pai",
  start_date: "Início",
  end_date: "Término",
  estimated_hours: "Horas estimadas",
  actual_hours: "Horas realizadas",
  progress: "Progresso",
  // Finance
  amount: "Valor",
  net_amount: "Valor líquido",
  gross_amount: "Valor bruto",
  due_at_date: "Vence em",
  paid_at: "Pago em",
  category_id: "Categoria",
  cost_center_id: "Centro de custo",
  legal_entity_id: "Empresa (CNPJ)",
  bank_account_id: "Conta bancária",
  direction: "Direção",
  payment_method: "Método de pagamento",
  reference: "Referência",
  // Contracts / quotes / proposals
  contract_id: "Contrato",
  deal_id_ref: "Negócio",
  start_at: "Início da vigência",
  end_at: "Fim da vigência",
  total: "Total",
  subtotal: "Subtotal",
  discount: "Desconto",
  tax: "Imposto",
  valid_until: "Válido até",
  // Products / services / recurring plans
  sku: "SKU",
  unit_price: "Preço unitário",
  unit: "Unidade",
  billing_cycle: "Ciclo de cobrança",
  interval: "Intervalo",
  interval_count: "Nº de intervalos",
  price: "Preço",
  barcode: "Código de barras",
  quantity: "Quantidade",
  active: "Ativo",
  trial_days: "Dias de teste",
  next_billing_at: "Próxima cobrança em",
  period_start: "Início do período",
  period_end: "Fim do período",
  version: "Versão",
  slug: "Identificador (slug)",
  sort_order: "Ordem de exibição",
  kind: "Tipo",
  terms: "Termos",
  variables: "Variáveis",
  template_id: "Modelo",
  locked: "Bloqueado",
  archived: "Arquivado",
  position: "Posição",
  metadata: "Metadados técnicos",
  attachments: "Anexos",
  mentions: "Menções",
  location: "Local",
  provider: "Provedor",
  role: "Papel",
  // Responsáveis e pessoas
  assigned_to: "Responsável",
  created_by: "Criado por",
  approved_by: "Aprovado por",
  full_name: "Nome completo",
  photo_url: "Foto",
  delivery_owner_id: "Responsável pela entrega",
  relationship_owner_id: "Responsável pelo relacionamento",
  relationship_status: "Status do relacionamento",
  assignee_ids: "Responsáveis",
  // Datas / marcos
  accepted_at: "Aceito em",
  applied_at: "Candidatura em",
  approved_at: "Aprovado em",
  cancelled_at: "Cancelado em",
  decided_at: "Decidido em",
  declined_at: "Recusado em",
  expires_at: "Expira em",
  filled_at: "Preenchido em",
  issued_at: "Emitido em",
  moved_at: "Movido em",
  opened_at: "Aberto em",
  sent_at: "Enviado em",
  scheduled_at: "Agendado para",
  scheduled_for: "Agendado para",
  signed_at: "Assinado em",
  starts_at: "Início",
  ends_at: "Término",
  next_action_at: "Próxima ação em",
  last_touch_at: "Último contato em",
  captured_at: "Capturado em",
  competence_date: "Data de competência",
  retention_until: "Retenção até",
  lgpd_redacted_at: "Anonimizado (LGPD) em",
  nurture_started_at: "Nutrição iniciada em",
  outcome_set_at: "Resultado definido em",
  relink_checked_at: "Revinculação checada em",
  reminder_1h_sent_at: "Lembrete de 1h enviado em",
  reminder_d1_sent_at: "Lembrete de 1 dia enviado em",
  self_scheduled_at: "Autoagendado em",
  self_schedule_expires_at: "Autoagendamento expira em",
  // Financeiro
  amount_total: "Valor total",
  total_amount: "Valor total",
  total_value: "Valor total",
  monthly_value: "Valor mensal",
  paid_amount: "Valor pago",
  bill_amount: "Valor da fatura",
  discount_total: "Desconto total",
  tax_total: "Impostos",
  tax_rate: "Alíquota (%)",
  invoice_number: "Número da fatura",
  installment_number: "Nº da parcela",
  installment_total: "Total de parcelas",
  parent_entry_id: "Lançamento pai",
  financial_entry_id: "Lançamento financeiro",
  subscription_id: "Assinatura",
  quote_id: "Cotação",
  service_id: "Serviço",
  list_id: "Lista",
  pool_id: "Pool de talentos",
  origin_id: "Origem (ID)",
  origin_type: "Tipo de origem",
  external_ref: "Referência externa",
  gateway: "Gateway de pagamento",
  gateway_mode: "Modo do gateway",
  payment_url: "Link de pagamento",
  payment_link_url: "Link de pagamento",
  payment_session_id: "Sessão de pagamento",
  payment_day: "Dia de pagamento",
  payment_terms: "Condições de pagamento",
  boleto_barcode: "Código de barras do boleto",
  boleto_digitable_line: "Linha digitável do boleto",
  pix_key: "Chave Pix",
  pix_key_type: "Tipo da chave Pix",
  pix_copy_paste: "Pix copia e cola",
  pix_qr_code: "QR Code Pix",
  favored_name: "Favorecido",
  favored_document: "Documento do favorecido",
  failure_reason: "Motivo da falha",
  billable: "Faturável",
  planned_cost: "Custo planejado",
  planned_hours: "Horas planejadas",
  duration_min: "Duração (min)",
  duration_ms: "Duração (ms)",
  // Contratos / assinatura
  auto_renew: "Renovação automática",
  notice_days: "Aviso prévio (dias)",
  cure_period_days: "Prazo de cura (dias)",
  trial_period_days: "Período de experiência (dias)",
  unilateral_termination_notice_days: "Aviso de rescisão unilateral (dias)",
  expense_reimbursement_days: "Reembolso de despesas (dias)",
  confidentiality_term_months: "Prazo de sigilo (meses)",
  late_fee_percent: "Multa por atraso (%)",
  late_interest_monthly_percent: "Juros mensais por atraso (%)",
  penalty_percent: "Multa rescisória (%)",
  readjustment_index: "Índice de reajuste",
  readjustment_period: "Periodicidade do reajuste",
  service_type: "Tipo de serviço",
  service_scope: "Escopo do serviço",
  service_location: "Local de execução",
  governing_law: "Lei aplicável",
  jurisdiction: "Foro",
  hours_per_month: "Horas por mês",
  body_html: "Corpo do documento",
  number: "Número",
  counterparty_company_id: "Empresa contraparte",
  counterparty_legal_entity_id: "Empresa contraparte (CNPJ)",
  contracting_legal_entity_id: "Empresa contratante (CNPJ)",
  parent_contract_id: "Contrato principal",
  source_file_path: "Arquivo de origem",
  imported_from: "Importado de",
  import_confidence: "Confiança da importação (IA)",
  public_token: "Token do link público",
  signature_provider: "Provedor de assinatura",
  signature_name: "Nome da assinatura",
  signature_document_id: "Documento no provedor de assinatura",
  signature_operation_id: "Operação de assinatura",
  signed_pdf_path: "PDF assinado",
  esign_document_id: "Documento de assinatura eletrônica",
  // Atividades / comunicação
  email_direction: "Direção do e-mail",
  email_status: "Status do e-mail",
  disposition: "Desfecho da ligação",
  outcome: "Resultado",
  meeting_id: "Reunião",
  meeting_key: "Chave da reunião",
  meeting_location: "Local da reunião",
  meeting_outcome: "Resultado da reunião",
  meet_url: "Link da reunião",
  recording_url: "Gravação",
  recording_sid: "ID da gravação",
  recording_channels: "Canais da gravação",
  recording_duration_seconds: "Duração da gravação (s)",
  transcript: "Transcrição",
  transcription: "Transcrição",
  transcription_model: "Modelo de transcrição",
  transcription_status: "Status da transcrição",
  completed: "Concluída",
  task_priority: "Prioridade da tarefa",
  task_status: "Status da tarefa",
  cadence: "Cadência",
  connection_id: "Conexão",
  custom_field_values: "Campos personalizados",
  custom_status_id: "Status personalizado",
  view_count: "Visualizações",
  slots: "Horários",
  offered_slots: "Horários oferecidos",
  self_schedule_token: "Token de autoagendamento",
  auto_rescheduled_from: "Reagendado de",
  async_questions_snapshot: "Perguntas assíncronas (registro)",
  panel_interviewer_ids: "Banca de entrevistadores",
  interviewer_id: "Entrevistador",
  interview_kit_id: "Kit de entrevista",
  recruiter_id: "Recrutador",
  hiring_manager_id: "Gestor da vaga",
  candidate_id: "Candidato",
  application_id: "Candidatura",
  job_id: "Vaga",
  stage_value: "Etapa",
  rejection_reason: "Motivo da reprovação",
  // SLA (tickets)
  sla_first_response_at: "Primeira resposta em",
  sla_first_response_due_at: "SLA de primeira resposta até",
  sla_first_response_breached: "SLA de primeira resposta violado",
  sla_resolution_breached: "SLA de resolução violado",
  // Relacionamentos genéricos
  related_company_id: "Empresa relacionada",
  related_contact_id: "Contato relacionado",
  related_deal_id: "Negócio relacionado",
  related_lead_id: "Lead relacionado",
  related_ticket_id: "Chamado relacionado",
  projects: "Projetos",
  // Candidatos / talentos
  about: "Sobre",
  headline: "Resumo profissional",
  current_company: "Empresa atual",
  current_company_data: "Dados da empresa atual",
  current_position: "Cargo atual",
  seniority: "Senioridade",
  employment_type: "Tipo de contratação",
  remote_mode: "Modelo de trabalho",
  skills: "Competências",
  skills_detailed: "Competências detalhadas",
  languages: "Idiomas",
  education: "Formação",
  experiences: "Experiências",
  certifications: "Certificações",
  publications: "Publicações",
  volunteering: "Trabalho voluntário",
  recommendations: "Recomendações",
  recent_activity: "Atividade recente",
  external_links: "Links externos",
  cv_url: "Currículo",
  cv_parsed: "Currículo processado",
  open_to_work: "Aberto a oportunidades",
  connection_degree: "Grau de conexão",
  capture_version: "Versão da captura",
  available_actions: "Ações disponíveis",
  provider_applicant_id: "ID do candidato no provedor",
  salary_min: "Salário mínimo",
  salary_max: "Salário máximo",
  salary_currency: "Moeda do salário",
  requirements: "Requisitos",
  dei_gender: "Gênero (D&I)",
  dei_race: "Raça/cor (D&I)",
  dei_disability: "Deficiência (D&I)",
  dei_lgbtqia: "LGBTQIA+ (D&I)",
  // LinkedIn
  linkedin_apply_type: "Tipo de candidatura (LinkedIn)",
  linkedin_apply_url: "URL de candidatura (LinkedIn)",
  linkedin_company_id: "Empresa no LinkedIn (ID)",
  linkedin_company_name: "Empresa no LinkedIn",
  linkedin_employment_status: "Tipo de vínculo (LinkedIn)",
  linkedin_location_id: "Localidade no LinkedIn (ID)",
  linkedin_location_name: "Localidade (LinkedIn)",
  linkedin_notification_email: "E-mail de notificação (LinkedIn)",
  linkedin_workplace: "Modelo de trabalho (LinkedIn)",
  // IA
  ai_summary: "Resumo (IA)",
  ai_score: "Score (IA)",
  ai_match_score: "Score de match (IA)",
  ai_match_summary: "Resumo do match (IA)",
  ai_strengths: "Pontos fortes (IA)",
  ai_concerns: "Pontos de atenção (IA)",
  ai_followups: "Perguntas de follow-up (IA)",
  ai_recommendation: "Recomendação (IA)",
  ai_model: "Modelo de IA",
  ai_generated_at: "Gerado por IA em",
};

/**
 * Rótulos que dependem da entidade — evita traduções erradas do dicionário
 * global (ex.: `title` = "Cargo" em contatos, mas "Título" em contratos).
 */
export const ENTITY_LABEL_OVERRIDES: Record<string, Record<string, string>> = {
  contracts: CONTRACT_FIELD_LABELS,
  quotes: { title: "Título da cotação" },
  proposals: { title: "Título da proposta" },
  ats_jobs: { title: "Título da vaga" },
  project_tasks: { title: "Título da tarefa" },
  project_milestones: { title: "Título do marco" },
  tickets: { title: "Título do chamado" },
  activities: { title: "Título da atividade" },
};

export const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function toLabel(col: string, entity?: string): string {
  const override = entity ? ENTITY_LABEL_OVERRIDES[entity]?.[col] : undefined;
  if (override) return override;
  if (LABELS[col]) return LABELS[col];
  return col.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * Colunas legadas que representam o MESMO dado de uma coluna canônica.
 * Fonte única da verdade para: rótulo distinto, marcação de campo de sistema
 * e trava de UI contra campos duplicados por alias.
 */
export const FIELD_ALIASES: Record<string, string> = {
  company_name: "company_id",
  assigned_user_id: "assigned_to",
};

/** Aliases legados são sempre tratados como campos de sistema (bloco recolhido). */
export const LEGACY_SYSTEM_FIELDS: ReadonlySet<string> = new Set(Object.keys(FIELD_ALIASES));

export function isLegacyAlias(col: string): boolean {
  return col in FIELD_ALIASES;
}

/** Retorna a coluna canônica de um alias, ou a própria coluna. */
export function canonicalOf(col: string): string {
  return FIELD_ALIASES[col] ?? col;
}
