// Rótulos em PT-BR dos recursos do catálogo de permissões (`permissions.resource`).
// Usado pela matriz de /settings/permissions para não exibir slugs em inglês.
// Fallback: o slug é formatado legivelmente (ver prettyResource).

export const RESOURCE_LABELS_PT: Record<string, string> = {
  activities: "Atividades",
  allocations: "Alocações",
  analytics: "Analytics",
  "analytics.dashboards": "Dashboards",
  "analytics.insights": "Insights",
  "analytics.reports": "Relatórios",
  approvals: "Aprovações",
  audit: "Auditoria",
  "automation.email_templates": "Modelos de e-mail",
  "automation.macros": "Macros",
  "automation.rotation": "Rodízio de leads",
  "automation.sequences": "Sequências",
  "automation.sla": "SLA",
  bank_accounts: "Contas bancárias",
  banking: "Open Banking",
  benefits: "Benefícios",
  billing: "Planos e cobrança",
  booking: "Agendamentos",
  branding: "White-label",
  briefing: "Briefing diário",
  calendars: "Calendários",
  candidates: "Candidatos",
  careers: "Página de carreiras",
  "catalog.services": "Serviços",
  categories: "Categorias",
  charging_templates: "Modelos de cobrança",
  clauses: "Biblioteca de cláusulas",
  communications: "Comunicações",
  companies: "Empresas",
  compliance: "Compliance",
  contacts: "Contatos",
  contracts: "Contratos",
  copilot: "Copilot",
  cost_centers: "Centros de custo",
  custom_objects: "Objetos custom",
  custom_properties: "Propriedades",
  dashboard: "Dashboard",
  deal_delivery: "Entrega dos negócios",
  deals: "Negócios",
  dei_analytics: "Analytics de diversidade",
  documents: "Documentos",
  dunning: "Cobrança (dunning)",
  email_accounts: "Contas de e-mail",
  emails: "E-mails",
  entries: "Lançamentos",
  esign: "Assinaturas eletrônicas",
  files: "Arquivos",
  folders: "Pastas",
  fraud_flags: "Alertas de fraude",
  goals: "Metas",
  home: "Início",
  hubspot_sync: "Sincronização HubSpot",
  hunting: "Prospecção",
  "hunting.captures": "Prospecção/Capturas",
  "hunting.observability": "Prospecção/Observabilidade",
  "hunting.search": "Prospecção/Busca",
  "hunting.templates": "Prospecção/Modelos",
  import: "Importação",
  inbox: "Caixa de entrada",
  "inbox.chat": "Caixa de entrada/Chat",
  "inbox.email": "Caixa de entrada/E-mail",
  "inbox.whatsapp": "Caixa de entrada/WhatsApp",
  incidents: "Incidentes",
  insights: "Insights",
  integrations: "Integrações",
  interview_kits: "Kits de entrevista",
  interviews: "Entrevistas",
  invoices: "Faturas",
  jobs: "Vagas",
  kb: "Base de conhecimento",
  "kb.articles": "Base de conhecimento/Artigos",
  language: "Idioma",
  leads: "Leads",
  legal_entities: "Entidades legais",
  legal_entity_groups: "Grupos empresariais",
  linkedin: "LinkedIn",
  lists: "Listas",
  macros: "Macros",
  "marketing.campaigns": "Campanhas",
  "marketing.forms": "Formulários",
  "marketing.landing_pages": "Landing pages",
  "marketing.sdr_agent": "Agente SDR",
  marketplace: "Marketplace",
  match_scores: "Match de candidatos",
  meetings: "Reuniões",
  members: "Membros",
  milestones: "Marcos",
  modules: "Módulos",
  my_team: "Meu time",
  my_work: "Meu trabalho",
  nfse: "NFS-e",
  notes: "Notas",
  notetaker: "Notetaker",
  offboarding: "Offboarding",
  offers: "Propostas de contratação",
  onboarding: "Onboarding",
  onboarding_templates: "Modelos de onboarding",
  one_on_ones: "1:1",
  payments: "Pagamentos",
  people: "Pessoas",
  "performance.goals": "Desempenho/Metas",
  "performance.one_on_ones": "Desempenho/1:1",
  "performance.reviews": "Desempenho/Avaliações",
  pipelines: "Pipelines",
  portal: "Portal do cliente",
  project_updates: "Acompanhamentos de projeto",
  projects: "Projetos",
  prospecting_cadences: "Prospecção/Cadências",
  prospecting_enrichment: "Prospecção/Enriquecimento",
  prospecting_playbooks: "Prospecção/Playbooks",
  prospecting_questionnaires: "Prospecção/Questionários",
  prospecting_queue: "Prospecção/Filas",
  prospecting_scoring: "Prospecção/Scoring",
  prospecting_scripts: "Prospecção/Scripts",
  prospecting_search: "Prospecção/Busca",
  prospecting_voice: "Prospecção/Voz",
  quotes: "Cotações",
  rbac_diagnostics: "Diagnóstico de acesso",
  recurrences: "Recorrências",
  reports: "Relatórios",
  reviews: "Avaliações",
  roles: "Cargos e permissões",
  scheduling: "Agenda",
  scorecards: "Scorecards",
  services: "Serviços",
  settings: "Configurações",
  sla: "SLA",
  snippets: "Snippets",
  sourcing: "Sourcing",
  "sourcing.analytics": "Sourcing/Analytics",
  "sourcing.inbox": "Sourcing/Caixa de entrada",
  "sourcing.multi_posting": "Sourcing/Multi-postagem",
  "sourcing.pools": "Sourcing/Talent pools",
  "sourcing.referrals": "Sourcing/Indicações",
  "sourcing.sequences": "Sourcing/Sequências",
  spaces: "Espaços",
  stage_emails: "E-mails por etapa",
  surveys: "Pesquisas",
  task_queues: "Filas de tarefas",
  tasks: "Tarefas",
  tickets: "Tickets",
  time_entries: "Apontamentos",
  timesheet: "Timesheet",
  user_groups: "Grupos de usuários",
  webhooks: "Webhooks",
  "wellbeing.assessments": "Avaliações psicossociais",
  "wellbeing.incidents": "Incidentes de bem-estar",
  whatsapp: "WhatsApp",
  widget: "Widget",
  workflows: "Workflows",
};
