DROP POLICY IF EXISTS kb_articles_perm_delete ON public.kb_articles;
CREATE POLICY kb_articles_perm_delete ON public.kb_articles AS RESTRICTIVE FOR DELETE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techservice.kb.delete.workspace'::text)));
DROP POLICY IF EXISTS kb_articles_perm_update ON public.kb_articles;
CREATE POLICY kb_articles_perm_update ON public.kb_articles AS RESTRICTIVE FOR UPDATE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techservice.kb.update.workspace'::text)));
DROP POLICY IF EXISTS people_benefits_perm_delete ON public.people_benefits;
CREATE POLICY people_benefits_perm_delete ON public.people_benefits AS RESTRICTIVE FOR DELETE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.benefits.delete.workspace'::text)));
DROP POLICY IF EXISTS people_benefits_perm_select ON public.people_benefits;
CREATE POLICY people_benefits_perm_select ON public.people_benefits AS RESTRICTIVE FOR SELECT TO authenticated USING (((owner_id = auth.uid()) OR is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.benefits.view.workspace'::text)));
DROP POLICY IF EXISTS people_benefits_perm_update ON public.people_benefits;
CREATE POLICY people_benefits_perm_update ON public.people_benefits AS RESTRICTIVE FOR UPDATE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.benefits.update.workspace'::text)));
DROP POLICY IF EXISTS people_docs_perm_delete ON public.people_documents;
CREATE POLICY people_docs_perm_delete ON public.people_documents AS RESTRICTIVE FOR DELETE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.documents.delete.workspace'::text)));
DROP POLICY IF EXISTS people_docs_perm_select ON public.people_documents;
CREATE POLICY people_docs_perm_select ON public.people_documents AS RESTRICTIVE FOR SELECT TO authenticated USING (((owner_id = auth.uid()) OR is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.documents.view.workspace'::text)));
DROP POLICY IF EXISTS people_docs_perm_update ON public.people_documents;
CREATE POLICY people_docs_perm_update ON public.people_documents AS RESTRICTIVE FOR UPDATE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.documents.update.workspace'::text)));
DROP POLICY IF EXISTS people_goals_perm_delete ON public.people_goals;
CREATE POLICY people_goals_perm_delete ON public.people_goals AS RESTRICTIVE FOR DELETE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.goals.delete.workspace'::text)));
DROP POLICY IF EXISTS people_goals_perm_select ON public.people_goals;
CREATE POLICY people_goals_perm_select ON public.people_goals AS RESTRICTIVE FOR SELECT TO authenticated USING (((owner_id = auth.uid()) OR is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.goals.view.workspace'::text) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.goals.view.own'::text)));
DROP POLICY IF EXISTS people_goals_perm_update ON public.people_goals;
CREATE POLICY people_goals_perm_update ON public.people_goals AS RESTRICTIVE FOR UPDATE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.goals.update.workspace'::text) OR ((owner_id = auth.uid()) AND user_has_permission(auth.uid(), workspace_id, 'techpeople.goals.update.own'::text))));
DROP POLICY IF EXISTS people_incidents_perm_delete ON public.people_incidents;
CREATE POLICY people_incidents_perm_delete ON public.people_incidents AS RESTRICTIVE FOR DELETE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.incidents.delete.workspace'::text)));
DROP POLICY IF EXISTS people_incidents_select_gate ON public.people_incidents;
CREATE POLICY people_incidents_select_gate ON public.people_incidents AS RESTRICTIVE FOR SELECT TO authenticated USING ((((person_id IS NOT NULL) AND can_view_person_sensitive(person_id)) OR ((person_id IS NULL) AND is_workspace_admin_v2(workspace_id, auth.uid()))));
DROP POLICY IF EXISTS people_incidents_update_gate ON public.people_incidents;
CREATE POLICY people_incidents_update_gate ON public.people_incidents AS RESTRICTIVE FOR UPDATE TO authenticated USING ((((person_id IS NOT NULL) AND can_manage_person(person_id)) OR ((person_id IS NULL) AND is_workspace_admin_v2(workspace_id, auth.uid())))) WITH CHECK ((((person_id IS NOT NULL) AND can_manage_person(person_id)) OR ((person_id IS NULL) AND is_workspace_admin_v2(workspace_id, auth.uid()))));
DROP POLICY IF EXISTS people_1x1_perm_delete ON public.people_one_on_ones;
CREATE POLICY people_1x1_perm_delete ON public.people_one_on_ones AS RESTRICTIVE FOR DELETE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.one_on_ones.delete.workspace'::text)));
DROP POLICY IF EXISTS people_1x1_perm_select ON public.people_one_on_ones;
CREATE POLICY people_1x1_perm_select ON public.people_one_on_ones AS RESTRICTIVE FOR SELECT TO authenticated USING (((owner_id = auth.uid()) OR is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.one_on_ones.view.workspace'::text) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.one_on_ones.view.own'::text)));
DROP POLICY IF EXISTS people_1x1_perm_update ON public.people_one_on_ones;
CREATE POLICY people_1x1_perm_update ON public.people_one_on_ones AS RESTRICTIVE FOR UPDATE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.one_on_ones.update.workspace'::text) OR ((owner_id = auth.uid()) AND user_has_permission(auth.uid(), workspace_id, 'techpeople.one_on_ones.update.own'::text))));
DROP POLICY IF EXISTS people_reviews_perm_delete ON public.people_reviews;
CREATE POLICY people_reviews_perm_delete ON public.people_reviews AS RESTRICTIVE FOR DELETE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.reviews.delete.workspace'::text)));
DROP POLICY IF EXISTS people_reviews_perm_select ON public.people_reviews;
CREATE POLICY people_reviews_perm_select ON public.people_reviews AS RESTRICTIVE FOR SELECT TO authenticated USING (((owner_id = auth.uid()) OR is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.reviews.view.workspace'::text)));
DROP POLICY IF EXISTS people_reviews_perm_update ON public.people_reviews;
CREATE POLICY people_reviews_perm_update ON public.people_reviews AS RESTRICTIVE FOR UPDATE TO authenticated USING ((is_workspace_admin_v2(workspace_id, auth.uid()) OR user_has_permission(auth.uid(), workspace_id, 'techpeople.reviews.update.workspace'::text)));