// Ordem canônica dos campos por entidade, espelhando (o mais próximo possível)
// a ordem em que aparecem nos formulários de criação usados no app
// (quick-create-*, create-*-dialog). Serve para o ExtraFieldsEditor do
// workflow renderizar os campos em uma sequência reconhecível pelo usuário
// no lugar da ordem "amigável" (select→outros→data, alfabético) devolvida
// pelo catálogo.
//
// Campos ausentes do mapa canônico caem depois, preservando a ordem original.

import type { WorkflowWritableTable } from "./types";

type OrderMap = Partial<Record<WorkflowWritableTable, string[]>>;

const ORDER: OrderMap = {
  contracts: [
    "role",
    "type",
    "title",
    "contract_number",
    "status",
    "company_id",
    "counterparty_company_id",
    "contact_id",
    "primary_contact_id",
    "deal_id",
    "parent_contract_id",
    "start_at",
    "end_at",
    "value",
    "currency",
    "description",
    "notes",
  ],
  companies: [
    "name",
    "domain",
    "website",
    "cnpj",
    "industry",
    "size",
    "type",
    "phone",
    "city",
    "state",
    "country",
    "cep",
    "address",
    "assigned_user_id",
    "description",
    "notes",
  ],
  contacts: [
    "first_name",
    "last_name",
    "email",
    "phone",
    "mobile_phone",
    "job_title",
    "company_id",
    "company_name",
    "source",
    "status",
    "lifecyclestage",
    "assigned_user_id",
    "city",
    "state",
    "country",
    "linkedin_url",
    "notes",
  ],
  leads: [
    "first_name",
    "last_name",
    "email",
    "phone",
    "company_name",
    "company_id",
    "source",
    "status",
    "score",
    "pipeline_id",
    "stage",
    "assigned_user_id",
    "notes",
  ],
  deals: [
    "name",
    "pipeline_id",
    "stage",
    "stage_id",
    "assigned_user_id",
    "expected_close_date",
    "company_id",
    "primary_contact_id",
    "contact_id",
    "value",
    "currency",
    "dealtype",
    "hs_priority",
    "description",
  ],
  tickets: [
    "subject",
    "priority",
    "status",
    "pipeline_id",
    "stage",
    "channel",
    "category",
    "subcategory",
    "assignee_id",
    "contact_id",
    "company_id",
    "deal_id",
    "due_at",
    "sla_policy_id",
    "tags",
    "body",
    "description",
  ],
  activities: [
    "activity_type",
    "subject",
    "assignee_id",
    "due_date",
    "due_at",
    "contact_id",
    "company_id",
    "deal_id",
    "body",
    "description",
  ],
  projects: [
    "name",
    "description",
    "status",
    "company_id",
    "contact_id",
    "deal_id",
    "assigned_user_id",
    "start_date",
    "end_date",
    "due_date",
    "estimated_hours",
    "progress",
  ],
  project_tasks: [
    "title",
    "name",
    "description",
    "status",
    "priority",
    "project_id",
    "milestone_id",
    "parent_task_id",
    "assignee_id",
    "assigned_user_id",
    "start_date",
    "due_date",
    "estimated_hours",
    "actual_hours",
    "progress",
  ],
  project_milestones: [
    "name",
    "description",
    "status",
    "project_id",
    "due_date",
    "start_date",
    "end_date",
  ],
  financial_entries: [
    "direction",
    "description",
    "amount",
    "gross_amount",
    "net_amount",
    "category_id",
    "cost_center_id",
    "legal_entity_id",
    "bank_account_id",
    "reference_date",
    "due_at",
    "due_at_date",
    "paid_at",
    "payment_method",
    "reference",
    "company_id",
    "contact_id",
    "deal_id",
    "contract_id",
    "notes",
  ],
  quotes: [
    "name",
    "title",
    "status",
    "deal_id",
    "company_id",
    "contact_id",
    "valid_until",
    "subtotal",
    "discount",
    "tax",
    "total",
    "currency",
    "notes",
    "description",
  ],
  proposals: [
    "name",
    "title",
    "status",
    "deal_id",
    "company_id",
    "contact_id",
    "valid_until",
    "total",
    "currency",
    "description",
    "notes",
  ],
  services: [
    "name",
    "description",
    "type",
    "billing_cycle",
    "interval",
    "unit",
    "unit_price",
    "currency",
    "start_at",
    "end_at",
  ],
  ats_jobs: [
    "title",
    "status",
    "department",
    "seniority",
    "employment_type",
    "location",
    "remote",
    "hiring_manager_id",
    "owner_id",
    "company_id",
    "deal_id",
    "opened_at",
    "closed_at",
    "description",
  ],
  ats_candidates: [
    "first_name",
    "last_name",
    "email",
    "phone",
    "current_title",
    "current_company",
    "location",
    "source",
    "status",
    "owner_id",
    "linkedin_url",
    "notes",
  ],
  ats_applications: [
    "job_id",
    "candidate_id",
    "stage",
    "status",
    "source",
    "owner_id",
    "applied_at",
    "notes",
  ],
  ats_interviews: [
    "application_id",
    "candidate_id",
    "job_id",
    "type",
    "status",
    "scheduled_at",
    "duration_min",
    "interviewer_id",
    "location",
    "notes",
  ],
};

/**
 * Reordena `fields` colocando primeiro (na ordem canônica) os que aparecem no
 * mapa da entidade; o restante mantém a ordem original recebida.
 */
export function sortFieldsByCanonicalOrder<T extends { name: string }>(
  entity: WorkflowWritableTable,
  fields: T[],
): T[] {
  const canonical = ORDER[entity];
  if (!canonical || canonical.length === 0) return fields;

  const rank = new Map<string, number>();
  canonical.forEach((name, i) => rank.set(name, i));

  const known: T[] = [];
  const unknown: T[] = [];
  for (const f of fields) {
    if (rank.has(f.name)) known.push(f);
    else unknown.push(f);
  }
  known.sort((a, b) => rank.get(a.name)! - rank.get(b.name)!);
  return [...known, ...unknown];
}
