/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveyTokenRouteImport } from './routes/survey.$token'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as QuoteTokenRouteImport } from './routes/quote.$token'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedDashboardsRouteImport } from './routes/_authenticated/dashboards'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedCommunicationsRouteImport } from './routes/_authenticated/communications'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedIntegrationsIndexRouteImport } from './routes/_authenticated/integrations.index'
import { Route as AuthenticatedTasksQueuesRouteImport } from './routes/_authenticated/tasks.queues'
import { Route as AuthenticatedSettingsWorkflowsRouteImport } from './routes/_authenticated/settings.workflows'
import { Route as AuthenticatedSettingsTeamsRouteImport } from './routes/_authenticated/settings.teams'
import { Route as AuthenticatedSettingsSurveysRouteImport } from './routes/_authenticated/settings.surveys'
import { Route as AuthenticatedSettingsSubscriptionsRouteImport } from './routes/_authenticated/settings.subscriptions'
import { Route as AuthenticatedSettingsSlaRouteImport } from './routes/_authenticated/settings.sla'
import { Route as AuthenticatedSettingsSequencesRouteImport } from './routes/_authenticated/settings.sequences'
import { Route as AuthenticatedSettingsSegmentsRouteImport } from './routes/_authenticated/settings.segments'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedSettingsScoringRouteImport } from './routes/_authenticated/settings.scoring'
import { Route as AuthenticatedSettingsRotationRouteImport } from './routes/_authenticated/settings.rotation'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings.roles'
import { Route as AuthenticatedSettingsRecurringRouteImport } from './routes/_authenticated/settings.recurring'
import { Route as AuthenticatedSettingsQuotesRouteImport } from './routes/_authenticated/settings.quotes'
import { Route as AuthenticatedSettingsProductsRouteImport } from './routes/_authenticated/settings.products'
import { Route as AuthenticatedSettingsPortalRouteImport } from './routes/_authenticated/settings.portal'
import { Route as AuthenticatedSettingsPlaybooksRouteImport } from './routes/_authenticated/settings.playbooks'
import { Route as AuthenticatedSettingsPipelinesRouteImport } from './routes/_authenticated/settings.pipelines'
import { Route as AuthenticatedSettingsMacrosRouteImport } from './routes/_authenticated/settings.macros'
import { Route as AuthenticatedSettingsGoalsRouteImport } from './routes/_authenticated/settings.goals'
import { Route as AuthenticatedSettingsFormsRouteImport } from './routes/_authenticated/settings.forms'
import { Route as AuthenticatedSettingsExportsRouteImport } from './routes/_authenticated/settings.exports'
import { Route as AuthenticatedSettingsEsignRouteImport } from './routes/_authenticated/settings.esign'
import { Route as AuthenticatedSettingsEnrichmentRouteImport } from './routes/_authenticated/settings.enrichment'
import { Route as AuthenticatedSettingsEmailTemplatesRouteImport } from './routes/_authenticated/settings.email-templates'
import { Route as AuthenticatedSettingsEmailRouteImport } from './routes/_authenticated/settings.email'
import { Route as AuthenticatedSettingsCustomPropertiesRouteImport } from './routes/_authenticated/settings.custom-properties'
import { Route as AuthenticatedSettingsCalendarsRouteImport } from './routes/_authenticated/settings.calendars'
import { Route as AuthenticatedSettingsBookingRouteImport } from './routes/_authenticated/settings.booking'
import { Route as AuthenticatedSettingsAuditLogRouteImport } from './routes/_authenticated/settings.audit-log'
import { Route as AuthenticatedLeadsImportHubspotRouteImport } from './routes/_authenticated/leads.import-hubspot'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'
import { Route as AuthenticatedIntegrationsSlugRouteImport } from './routes/_authenticated/integrations.$slug'
import { Route as AuthenticatedInboxWhatsappRouteImport } from './routes/_authenticated/inbox.whatsapp'
import { Route as AuthenticatedInboxEmailRouteImport } from './routes/_authenticated/inbox.email'
import { Route as AuthenticatedCampaignsWhatsappRouteImport } from './routes/_authenticated/campaigns.whatsapp'
import { Route as AuthenticatedCampaignsEmailRouteImport } from './routes/_authenticated/campaigns.email'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio/voice'
import { Route as ApiPublicOauthGoogleCallbackRouteImport } from './routes/api/public/oauth/google-callback'
import { Route as ApiPublicHooksWorkflowsTickRouteImport } from './routes/api/public/hooks/workflows-tick'
import { Route as ApiPublicHooksWhatsappCampaignTickRouteImport } from './routes/api/public/hooks/whatsapp-campaign-tick'
import { Route as ApiPublicHooksTwilioWhatsappStatusRouteImport } from './routes/api/public/hooks/twilio-whatsapp-status'
import { Route as ApiPublicHooksTwilioWhatsappRouteImport } from './routes/api/public/hooks/twilio-whatsapp'
import { Route as ApiPublicHooksSequencesTickRouteImport } from './routes/api/public/hooks/sequences-tick'
import { Route as ApiPublicHooksSegmentsTickRouteImport } from './routes/api/public/hooks/segments-tick'
import { Route as ApiPublicHooksScoringTickRouteImport } from './routes/api/public/hooks/scoring-tick'
import { Route as ApiPublicHooksScheduledExportsTickRouteImport } from './routes/api/public/hooks/scheduled-exports-tick'
import { Route as ApiPublicHooksHubspotTickRouteImport } from './routes/api/public/hooks/hubspot-tick'
import { Route as ApiPublicHooksEmailSyncTickRouteImport } from './routes/api/public/hooks/email-sync-tick'
import { Route as ApiPublicHooksEmailBroadcastTickRouteImport } from './routes/api/public/hooks/email-broadcast-tick'
import { Route as ApiPublicHooksCalendarTickRouteImport } from './routes/api/public/hooks/calendar-tick'
import { Route as ApiPublicFormsEmbedJsRouteImport } from './routes/api/public/forms/embed-js'
import { Route as ApiPublicFormsSlugRouteImport } from './routes/api/public/forms/$slug'
import { Route as ApiPublicBookingSlugRouteImport } from './routes/api/public/booking/$slug'
import { Route as ApiPublicFormsSlugSubmitRouteImport } from './routes/api/public/forms/$slug.submit'
import { Route as ApiPublicEmailUnsubscribeTokenRouteImport } from './routes/api/public/email/unsubscribe.$token'
import { Route as ApiPublicEmailPixelMessageIdRouteImport } from './routes/api/public/email/pixel.$messageId'
import { Route as ApiPublicEmailClickMessageIdRouteImport } from './routes/api/public/email/click.$messageId'
import { Route as ApiPublicBookingSlugSubmitRouteImport } from './routes/api/public/booking/$slug/submit'
import { Route as AuthenticatedTasksQueuesQueueIdPlayRouteImport } from './routes/_authenticated/tasks.queues.$queueId.play'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyTokenRoute = SurveyTokenRouteImport.update({
  id: '/survey/$token',
  path: '/survey/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteTokenRoute = QuoteTokenRouteImport.update({
  id: '/quote/$token',
  path: '/quote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardsRoute = AuthenticatedDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunicationsRoute =
  AuthenticatedCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedIntegrationsIndexRoute =
  AuthenticatedIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIntegrationsRoute,
  } as any)
const AuthenticatedTasksQueuesRoute =
  AuthenticatedTasksQueuesRouteImport.update({
    id: '/queues',
    path: '/queues',
    getParentRoute: () => AuthenticatedTasksRoute,
  } as any)
const AuthenticatedSettingsWorkflowsRoute =
  AuthenticatedSettingsWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTeamsRoute =
  AuthenticatedSettingsTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSurveysRoute =
  AuthenticatedSettingsSurveysRouteImport.update({
    id: '/surveys',
    path: '/surveys',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSubscriptionsRoute =
  AuthenticatedSettingsSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSlaRoute =
  AuthenticatedSettingsSlaRouteImport.update({
    id: '/sla',
    path: '/sla',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSequencesRoute =
  AuthenticatedSettingsSequencesRouteImport.update({
    id: '/sequences',
    path: '/sequences',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSegmentsRoute =
  AuthenticatedSettingsSegmentsRouteImport.update({
    id: '/segments',
    path: '/segments',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsScoringRoute =
  AuthenticatedSettingsScoringRouteImport.update({
    id: '/scoring',
    path: '/scoring',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsRotationRoute =
  AuthenticatedSettingsRotationRouteImport.update({
    id: '/rotation',
    path: '/rotation',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsRecurringRoute =
  AuthenticatedSettingsRecurringRouteImport.update({
    id: '/recurring',
    path: '/recurring',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsQuotesRoute =
  AuthenticatedSettingsQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProductsRoute =
  AuthenticatedSettingsProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPortalRoute =
  AuthenticatedSettingsPortalRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPlaybooksRoute =
  AuthenticatedSettingsPlaybooksRouteImport.update({
    id: '/playbooks',
    path: '/playbooks',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPipelinesRoute =
  AuthenticatedSettingsPipelinesRouteImport.update({
    id: '/pipelines',
    path: '/pipelines',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMacrosRoute =
  AuthenticatedSettingsMacrosRouteImport.update({
    id: '/macros',
    path: '/macros',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGoalsRoute =
  AuthenticatedSettingsGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsFormsRoute =
  AuthenticatedSettingsFormsRouteImport.update({
    id: '/forms',
    path: '/forms',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsExportsRoute =
  AuthenticatedSettingsExportsRouteImport.update({
    id: '/exports',
    path: '/exports',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsEsignRoute =
  AuthenticatedSettingsEsignRouteImport.update({
    id: '/esign',
    path: '/esign',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsEnrichmentRoute =
  AuthenticatedSettingsEnrichmentRouteImport.update({
    id: '/enrichment',
    path: '/enrichment',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsEmailTemplatesRoute =
  AuthenticatedSettingsEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsEmailRoute =
  AuthenticatedSettingsEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCustomPropertiesRoute =
  AuthenticatedSettingsCustomPropertiesRouteImport.update({
    id: '/custom-properties',
    path: '/custom-properties',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCalendarsRoute =
  AuthenticatedSettingsCalendarsRouteImport.update({
    id: '/calendars',
    path: '/calendars',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBookingRoute =
  AuthenticatedSettingsBookingRouteImport.update({
    id: '/booking',
    path: '/booking',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAuditLogRoute =
  AuthenticatedSettingsAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLeadsImportHubspotRoute =
  AuthenticatedLeadsImportHubspotRouteImport.update({
    id: '/import-hubspot',
    path: '/import-hubspot',
    getParentRoute: () => AuthenticatedLeadsRoute,
  } as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)
const AuthenticatedIntegrationsSlugRoute =
  AuthenticatedIntegrationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedIntegrationsRoute,
  } as any)
const AuthenticatedInboxWhatsappRoute =
  AuthenticatedInboxWhatsappRouteImport.update({
    id: '/inbox/whatsapp',
    path: '/inbox/whatsapp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInboxEmailRoute = AuthenticatedInboxEmailRouteImport.update({
  id: '/inbox/email',
  path: '/inbox/email',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsWhatsappRoute =
  AuthenticatedCampaignsWhatsappRouteImport.update({
    id: '/campaigns/whatsapp',
    path: '/campaigns/whatsapp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsEmailRoute =
  AuthenticatedCampaignsEmailRouteImport.update({
    id: '/campaigns/email',
    path: '/campaigns/email',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthGoogleCallbackRoute =
  ApiPublicOauthGoogleCallbackRouteImport.update({
    id: '/api/public/oauth/google-callback',
    path: '/api/public/oauth/google-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWorkflowsTickRoute =
  ApiPublicHooksWorkflowsTickRouteImport.update({
    id: '/api/public/hooks/workflows-tick',
    path: '/api/public/hooks/workflows-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappCampaignTickRoute =
  ApiPublicHooksWhatsappCampaignTickRouteImport.update({
    id: '/api/public/hooks/whatsapp-campaign-tick',
    path: '/api/public/hooks/whatsapp-campaign-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTwilioWhatsappStatusRoute =
  ApiPublicHooksTwilioWhatsappStatusRouteImport.update({
    id: '/api/public/hooks/twilio-whatsapp-status',
    path: '/api/public/hooks/twilio-whatsapp-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTwilioWhatsappRoute =
  ApiPublicHooksTwilioWhatsappRouteImport.update({
    id: '/api/public/hooks/twilio-whatsapp',
    path: '/api/public/hooks/twilio-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSequencesTickRoute =
  ApiPublicHooksSequencesTickRouteImport.update({
    id: '/api/public/hooks/sequences-tick',
    path: '/api/public/hooks/sequences-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSegmentsTickRoute =
  ApiPublicHooksSegmentsTickRouteImport.update({
    id: '/api/public/hooks/segments-tick',
    path: '/api/public/hooks/segments-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScoringTickRoute =
  ApiPublicHooksScoringTickRouteImport.update({
    id: '/api/public/hooks/scoring-tick',
    path: '/api/public/hooks/scoring-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScheduledExportsTickRoute =
  ApiPublicHooksScheduledExportsTickRouteImport.update({
    id: '/api/public/hooks/scheduled-exports-tick',
    path: '/api/public/hooks/scheduled-exports-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHubspotTickRoute =
  ApiPublicHooksHubspotTickRouteImport.update({
    id: '/api/public/hooks/hubspot-tick',
    path: '/api/public/hooks/hubspot-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailSyncTickRoute =
  ApiPublicHooksEmailSyncTickRouteImport.update({
    id: '/api/public/hooks/email-sync-tick',
    path: '/api/public/hooks/email-sync-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailBroadcastTickRoute =
  ApiPublicHooksEmailBroadcastTickRouteImport.update({
    id: '/api/public/hooks/email-broadcast-tick',
    path: '/api/public/hooks/email-broadcast-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCalendarTickRoute =
  ApiPublicHooksCalendarTickRouteImport.update({
    id: '/api/public/hooks/calendar-tick',
    path: '/api/public/hooks/calendar-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFormsEmbedJsRoute = ApiPublicFormsEmbedJsRouteImport.update({
  id: '/api/public/forms/embed-js',
  path: '/api/public/forms/embed-js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFormsSlugRoute = ApiPublicFormsSlugRouteImport.update({
  id: '/api/public/forms/$slug',
  path: '/api/public/forms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingSlugRoute = ApiPublicBookingSlugRouteImport.update({
  id: '/api/public/booking/$slug',
  path: '/api/public/booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFormsSlugSubmitRoute =
  ApiPublicFormsSlugSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => ApiPublicFormsSlugRoute,
  } as any)
const ApiPublicEmailUnsubscribeTokenRoute =
  ApiPublicEmailUnsubscribeTokenRouteImport.update({
    id: '/api/public/email/unsubscribe/$token',
    path: '/api/public/email/unsubscribe/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailPixelMessageIdRoute =
  ApiPublicEmailPixelMessageIdRouteImport.update({
    id: '/api/public/email/pixel/$messageId',
    path: '/api/public/email/pixel/$messageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailClickMessageIdRoute =
  ApiPublicEmailClickMessageIdRouteImport.update({
    id: '/api/public/email/click/$messageId',
    path: '/api/public/email/click/$messageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookingSlugSubmitRoute =
  ApiPublicBookingSlugSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => ApiPublicBookingSlugRoute,
  } as any)
const AuthenticatedTasksQueuesQueueIdPlayRoute =
  AuthenticatedTasksQueuesQueueIdPlayRouteImport.update({
    id: '/$queueId/play',
    path: '/$queueId/play',
    getParentRoute: () => AuthenticatedTasksQueuesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboards': typeof AuthenticatedDashboardsRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/notes': typeof AuthenticatedNotesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRoute
  '/book/$slug': typeof BookSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/campaigns/email': typeof AuthenticatedCampaignsEmailRoute
  '/campaigns/whatsapp': typeof AuthenticatedCampaignsWhatsappRoute
  '/inbox/email': typeof AuthenticatedInboxEmailRoute
  '/inbox/whatsapp': typeof AuthenticatedInboxWhatsappRoute
  '/integrations/$slug': typeof AuthenticatedIntegrationsSlugRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads/import-hubspot': typeof AuthenticatedLeadsImportHubspotRoute
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/booking': typeof AuthenticatedSettingsBookingRoute
  '/settings/calendars': typeof AuthenticatedSettingsCalendarsRoute
  '/settings/custom-properties': typeof AuthenticatedSettingsCustomPropertiesRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/settings/email-templates': typeof AuthenticatedSettingsEmailTemplatesRoute
  '/settings/enrichment': typeof AuthenticatedSettingsEnrichmentRoute
  '/settings/esign': typeof AuthenticatedSettingsEsignRoute
  '/settings/exports': typeof AuthenticatedSettingsExportsRoute
  '/settings/forms': typeof AuthenticatedSettingsFormsRoute
  '/settings/goals': typeof AuthenticatedSettingsGoalsRoute
  '/settings/macros': typeof AuthenticatedSettingsMacrosRoute
  '/settings/pipelines': typeof AuthenticatedSettingsPipelinesRoute
  '/settings/playbooks': typeof AuthenticatedSettingsPlaybooksRoute
  '/settings/portal': typeof AuthenticatedSettingsPortalRoute
  '/settings/products': typeof AuthenticatedSettingsProductsRoute
  '/settings/quotes': typeof AuthenticatedSettingsQuotesRoute
  '/settings/recurring': typeof AuthenticatedSettingsRecurringRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/rotation': typeof AuthenticatedSettingsRotationRoute
  '/settings/scoring': typeof AuthenticatedSettingsScoringRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/segments': typeof AuthenticatedSettingsSegmentsRoute
  '/settings/sequences': typeof AuthenticatedSettingsSequencesRoute
  '/settings/sla': typeof AuthenticatedSettingsSlaRoute
  '/settings/subscriptions': typeof AuthenticatedSettingsSubscriptionsRoute
  '/settings/surveys': typeof AuthenticatedSettingsSurveysRoute
  '/settings/teams': typeof AuthenticatedSettingsTeamsRoute
  '/settings/workflows': typeof AuthenticatedSettingsWorkflowsRoute
  '/tasks/queues': typeof AuthenticatedTasksQueuesRouteWithChildren
  '/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/booking/$slug': typeof ApiPublicBookingSlugRouteWithChildren
  '/api/public/forms/$slug': typeof ApiPublicFormsSlugRouteWithChildren
  '/api/public/forms/embed-js': typeof ApiPublicFormsEmbedJsRoute
  '/api/public/hooks/calendar-tick': typeof ApiPublicHooksCalendarTickRoute
  '/api/public/hooks/email-broadcast-tick': typeof ApiPublicHooksEmailBroadcastTickRoute
  '/api/public/hooks/email-sync-tick': typeof ApiPublicHooksEmailSyncTickRoute
  '/api/public/hooks/hubspot-tick': typeof ApiPublicHooksHubspotTickRoute
  '/api/public/hooks/scheduled-exports-tick': typeof ApiPublicHooksScheduledExportsTickRoute
  '/api/public/hooks/scoring-tick': typeof ApiPublicHooksScoringTickRoute
  '/api/public/hooks/segments-tick': typeof ApiPublicHooksSegmentsTickRoute
  '/api/public/hooks/sequences-tick': typeof ApiPublicHooksSequencesTickRoute
  '/api/public/hooks/twilio-whatsapp': typeof ApiPublicHooksTwilioWhatsappRoute
  '/api/public/hooks/twilio-whatsapp-status': typeof ApiPublicHooksTwilioWhatsappStatusRoute
  '/api/public/hooks/whatsapp-campaign-tick': typeof ApiPublicHooksWhatsappCampaignTickRoute
  '/api/public/hooks/workflows-tick': typeof ApiPublicHooksWorkflowsTickRoute
  '/api/public/oauth/google-callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/tasks/queues/$queueId/play': typeof AuthenticatedTasksQueuesQueueIdPlayRoute
  '/api/public/booking/$slug/submit': typeof ApiPublicBookingSlugSubmitRoute
  '/api/public/email/click/$messageId': typeof ApiPublicEmailClickMessageIdRoute
  '/api/public/email/pixel/$messageId': typeof ApiPublicEmailPixelMessageIdRoute
  '/api/public/email/unsubscribe/$token': typeof ApiPublicEmailUnsubscribeTokenRoute
  '/api/public/forms/$slug/submit': typeof ApiPublicFormsSlugSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboards': typeof AuthenticatedDashboardsRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/notes': typeof AuthenticatedNotesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRoute
  '/book/$slug': typeof BookSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/campaigns/email': typeof AuthenticatedCampaignsEmailRoute
  '/campaigns/whatsapp': typeof AuthenticatedCampaignsWhatsappRoute
  '/inbox/email': typeof AuthenticatedInboxEmailRoute
  '/inbox/whatsapp': typeof AuthenticatedInboxWhatsappRoute
  '/integrations/$slug': typeof AuthenticatedIntegrationsSlugRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads/import-hubspot': typeof AuthenticatedLeadsImportHubspotRoute
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/booking': typeof AuthenticatedSettingsBookingRoute
  '/settings/calendars': typeof AuthenticatedSettingsCalendarsRoute
  '/settings/custom-properties': typeof AuthenticatedSettingsCustomPropertiesRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/settings/email-templates': typeof AuthenticatedSettingsEmailTemplatesRoute
  '/settings/enrichment': typeof AuthenticatedSettingsEnrichmentRoute
  '/settings/esign': typeof AuthenticatedSettingsEsignRoute
  '/settings/exports': typeof AuthenticatedSettingsExportsRoute
  '/settings/forms': typeof AuthenticatedSettingsFormsRoute
  '/settings/goals': typeof AuthenticatedSettingsGoalsRoute
  '/settings/macros': typeof AuthenticatedSettingsMacrosRoute
  '/settings/pipelines': typeof AuthenticatedSettingsPipelinesRoute
  '/settings/playbooks': typeof AuthenticatedSettingsPlaybooksRoute
  '/settings/portal': typeof AuthenticatedSettingsPortalRoute
  '/settings/products': typeof AuthenticatedSettingsProductsRoute
  '/settings/quotes': typeof AuthenticatedSettingsQuotesRoute
  '/settings/recurring': typeof AuthenticatedSettingsRecurringRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/rotation': typeof AuthenticatedSettingsRotationRoute
  '/settings/scoring': typeof AuthenticatedSettingsScoringRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/segments': typeof AuthenticatedSettingsSegmentsRoute
  '/settings/sequences': typeof AuthenticatedSettingsSequencesRoute
  '/settings/sla': typeof AuthenticatedSettingsSlaRoute
  '/settings/subscriptions': typeof AuthenticatedSettingsSubscriptionsRoute
  '/settings/surveys': typeof AuthenticatedSettingsSurveysRoute
  '/settings/teams': typeof AuthenticatedSettingsTeamsRoute
  '/settings/workflows': typeof AuthenticatedSettingsWorkflowsRoute
  '/tasks/queues': typeof AuthenticatedTasksQueuesRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/public/booking/$slug': typeof ApiPublicBookingSlugRouteWithChildren
  '/api/public/forms/$slug': typeof ApiPublicFormsSlugRouteWithChildren
  '/api/public/forms/embed-js': typeof ApiPublicFormsEmbedJsRoute
  '/api/public/hooks/calendar-tick': typeof ApiPublicHooksCalendarTickRoute
  '/api/public/hooks/email-broadcast-tick': typeof ApiPublicHooksEmailBroadcastTickRoute
  '/api/public/hooks/email-sync-tick': typeof ApiPublicHooksEmailSyncTickRoute
  '/api/public/hooks/hubspot-tick': typeof ApiPublicHooksHubspotTickRoute
  '/api/public/hooks/scheduled-exports-tick': typeof ApiPublicHooksScheduledExportsTickRoute
  '/api/public/hooks/scoring-tick': typeof ApiPublicHooksScoringTickRoute
  '/api/public/hooks/segments-tick': typeof ApiPublicHooksSegmentsTickRoute
  '/api/public/hooks/sequences-tick': typeof ApiPublicHooksSequencesTickRoute
  '/api/public/hooks/twilio-whatsapp': typeof ApiPublicHooksTwilioWhatsappRoute
  '/api/public/hooks/twilio-whatsapp-status': typeof ApiPublicHooksTwilioWhatsappStatusRoute
  '/api/public/hooks/whatsapp-campaign-tick': typeof ApiPublicHooksWhatsappCampaignTickRoute
  '/api/public/hooks/workflows-tick': typeof ApiPublicHooksWorkflowsTickRoute
  '/api/public/oauth/google-callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/tasks/queues/$queueId/play': typeof AuthenticatedTasksQueuesQueueIdPlayRoute
  '/api/public/booking/$slug/submit': typeof ApiPublicBookingSlugSubmitRoute
  '/api/public/email/click/$messageId': typeof ApiPublicEmailClickMessageIdRoute
  '/api/public/email/pixel/$messageId': typeof ApiPublicEmailPixelMessageIdRoute
  '/api/public/email/unsubscribe/$token': typeof ApiPublicEmailUnsubscribeTokenRoute
  '/api/public/forms/$slug/submit': typeof ApiPublicFormsSlugSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/communications': typeof AuthenticatedCommunicationsRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dashboards': typeof AuthenticatedDashboardsRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/book/$slug': typeof BookSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/_authenticated/campaigns/email': typeof AuthenticatedCampaignsEmailRoute
  '/_authenticated/campaigns/whatsapp': typeof AuthenticatedCampaignsWhatsappRoute
  '/_authenticated/inbox/email': typeof AuthenticatedInboxEmailRoute
  '/_authenticated/inbox/whatsapp': typeof AuthenticatedInboxWhatsappRoute
  '/_authenticated/integrations/$slug': typeof AuthenticatedIntegrationsSlugRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/leads/import-hubspot': typeof AuthenticatedLeadsImportHubspotRoute
  '/_authenticated/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/_authenticated/settings/booking': typeof AuthenticatedSettingsBookingRoute
  '/_authenticated/settings/calendars': typeof AuthenticatedSettingsCalendarsRoute
  '/_authenticated/settings/custom-properties': typeof AuthenticatedSettingsCustomPropertiesRoute
  '/_authenticated/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/_authenticated/settings/email-templates': typeof AuthenticatedSettingsEmailTemplatesRoute
  '/_authenticated/settings/enrichment': typeof AuthenticatedSettingsEnrichmentRoute
  '/_authenticated/settings/esign': typeof AuthenticatedSettingsEsignRoute
  '/_authenticated/settings/exports': typeof AuthenticatedSettingsExportsRoute
  '/_authenticated/settings/forms': typeof AuthenticatedSettingsFormsRoute
  '/_authenticated/settings/goals': typeof AuthenticatedSettingsGoalsRoute
  '/_authenticated/settings/macros': typeof AuthenticatedSettingsMacrosRoute
  '/_authenticated/settings/pipelines': typeof AuthenticatedSettingsPipelinesRoute
  '/_authenticated/settings/playbooks': typeof AuthenticatedSettingsPlaybooksRoute
  '/_authenticated/settings/portal': typeof AuthenticatedSettingsPortalRoute
  '/_authenticated/settings/products': typeof AuthenticatedSettingsProductsRoute
  '/_authenticated/settings/quotes': typeof AuthenticatedSettingsQuotesRoute
  '/_authenticated/settings/recurring': typeof AuthenticatedSettingsRecurringRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/rotation': typeof AuthenticatedSettingsRotationRoute
  '/_authenticated/settings/scoring': typeof AuthenticatedSettingsScoringRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/segments': typeof AuthenticatedSettingsSegmentsRoute
  '/_authenticated/settings/sequences': typeof AuthenticatedSettingsSequencesRoute
  '/_authenticated/settings/sla': typeof AuthenticatedSettingsSlaRoute
  '/_authenticated/settings/subscriptions': typeof AuthenticatedSettingsSubscriptionsRoute
  '/_authenticated/settings/surveys': typeof AuthenticatedSettingsSurveysRoute
  '/_authenticated/settings/teams': typeof AuthenticatedSettingsTeamsRoute
  '/_authenticated/settings/workflows': typeof AuthenticatedSettingsWorkflowsRoute
  '/_authenticated/tasks/queues': typeof AuthenticatedTasksQueuesRouteWithChildren
  '/_authenticated/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/booking/$slug': typeof ApiPublicBookingSlugRouteWithChildren
  '/api/public/forms/$slug': typeof ApiPublicFormsSlugRouteWithChildren
  '/api/public/forms/embed-js': typeof ApiPublicFormsEmbedJsRoute
  '/api/public/hooks/calendar-tick': typeof ApiPublicHooksCalendarTickRoute
  '/api/public/hooks/email-broadcast-tick': typeof ApiPublicHooksEmailBroadcastTickRoute
  '/api/public/hooks/email-sync-tick': typeof ApiPublicHooksEmailSyncTickRoute
  '/api/public/hooks/hubspot-tick': typeof ApiPublicHooksHubspotTickRoute
  '/api/public/hooks/scheduled-exports-tick': typeof ApiPublicHooksScheduledExportsTickRoute
  '/api/public/hooks/scoring-tick': typeof ApiPublicHooksScoringTickRoute
  '/api/public/hooks/segments-tick': typeof ApiPublicHooksSegmentsTickRoute
  '/api/public/hooks/sequences-tick': typeof ApiPublicHooksSequencesTickRoute
  '/api/public/hooks/twilio-whatsapp': typeof ApiPublicHooksTwilioWhatsappRoute
  '/api/public/hooks/twilio-whatsapp-status': typeof ApiPublicHooksTwilioWhatsappStatusRoute
  '/api/public/hooks/whatsapp-campaign-tick': typeof ApiPublicHooksWhatsappCampaignTickRoute
  '/api/public/hooks/workflows-tick': typeof ApiPublicHooksWorkflowsTickRoute
  '/api/public/oauth/google-callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/_authenticated/tasks/queues/$queueId/play': typeof AuthenticatedTasksQueuesQueueIdPlayRoute
  '/api/public/booking/$slug/submit': typeof ApiPublicBookingSlugSubmitRoute
  '/api/public/email/click/$messageId': typeof ApiPublicEmailClickMessageIdRoute
  '/api/public/email/pixel/$messageId': typeof ApiPublicEmailPixelMessageIdRoute
  '/api/public/email/unsubscribe/$token': typeof ApiPublicEmailUnsubscribeTokenRoute
  '/api/public/forms/$slug/submit': typeof ApiPublicFormsSlugSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/analytics'
    | '/communications'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/dashboards'
    | '/deals'
    | '/integrations'
    | '/leads'
    | '/notes'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/tickets'
    | '/book/$slug'
    | '/portal/$token'
    | '/quote/$token'
    | '/sign/$token'
    | '/survey/$token'
    | '/campaigns/email'
    | '/campaigns/whatsapp'
    | '/inbox/email'
    | '/inbox/whatsapp'
    | '/integrations/$slug'
    | '/leads/$id'
    | '/leads/import-hubspot'
    | '/settings/audit-log'
    | '/settings/booking'
    | '/settings/calendars'
    | '/settings/custom-properties'
    | '/settings/email'
    | '/settings/email-templates'
    | '/settings/enrichment'
    | '/settings/esign'
    | '/settings/exports'
    | '/settings/forms'
    | '/settings/goals'
    | '/settings/macros'
    | '/settings/pipelines'
    | '/settings/playbooks'
    | '/settings/portal'
    | '/settings/products'
    | '/settings/quotes'
    | '/settings/recurring'
    | '/settings/roles'
    | '/settings/rotation'
    | '/settings/scoring'
    | '/settings/security'
    | '/settings/segments'
    | '/settings/sequences'
    | '/settings/sla'
    | '/settings/subscriptions'
    | '/settings/surveys'
    | '/settings/teams'
    | '/settings/workflows'
    | '/tasks/queues'
    | '/integrations/'
    | '/settings/'
    | '/api/public/booking/$slug'
    | '/api/public/forms/$slug'
    | '/api/public/forms/embed-js'
    | '/api/public/hooks/calendar-tick'
    | '/api/public/hooks/email-broadcast-tick'
    | '/api/public/hooks/email-sync-tick'
    | '/api/public/hooks/hubspot-tick'
    | '/api/public/hooks/scheduled-exports-tick'
    | '/api/public/hooks/scoring-tick'
    | '/api/public/hooks/segments-tick'
    | '/api/public/hooks/sequences-tick'
    | '/api/public/hooks/twilio-whatsapp'
    | '/api/public/hooks/twilio-whatsapp-status'
    | '/api/public/hooks/whatsapp-campaign-tick'
    | '/api/public/hooks/workflows-tick'
    | '/api/public/oauth/google-callback'
    | '/api/public/twilio/voice'
    | '/tasks/queues/$queueId/play'
    | '/api/public/booking/$slug/submit'
    | '/api/public/email/click/$messageId'
    | '/api/public/email/pixel/$messageId'
    | '/api/public/email/unsubscribe/$token'
    | '/api/public/forms/$slug/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/analytics'
    | '/communications'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/dashboards'
    | '/deals'
    | '/leads'
    | '/notes'
    | '/reports'
    | '/tasks'
    | '/tickets'
    | '/book/$slug'
    | '/portal/$token'
    | '/quote/$token'
    | '/sign/$token'
    | '/survey/$token'
    | '/campaigns/email'
    | '/campaigns/whatsapp'
    | '/inbox/email'
    | '/inbox/whatsapp'
    | '/integrations/$slug'
    | '/leads/$id'
    | '/leads/import-hubspot'
    | '/settings/audit-log'
    | '/settings/booking'
    | '/settings/calendars'
    | '/settings/custom-properties'
    | '/settings/email'
    | '/settings/email-templates'
    | '/settings/enrichment'
    | '/settings/esign'
    | '/settings/exports'
    | '/settings/forms'
    | '/settings/goals'
    | '/settings/macros'
    | '/settings/pipelines'
    | '/settings/playbooks'
    | '/settings/portal'
    | '/settings/products'
    | '/settings/quotes'
    | '/settings/recurring'
    | '/settings/roles'
    | '/settings/rotation'
    | '/settings/scoring'
    | '/settings/security'
    | '/settings/segments'
    | '/settings/sequences'
    | '/settings/sla'
    | '/settings/subscriptions'
    | '/settings/surveys'
    | '/settings/teams'
    | '/settings/workflows'
    | '/tasks/queues'
    | '/integrations'
    | '/settings'
    | '/api/public/booking/$slug'
    | '/api/public/forms/$slug'
    | '/api/public/forms/embed-js'
    | '/api/public/hooks/calendar-tick'
    | '/api/public/hooks/email-broadcast-tick'
    | '/api/public/hooks/email-sync-tick'
    | '/api/public/hooks/hubspot-tick'
    | '/api/public/hooks/scheduled-exports-tick'
    | '/api/public/hooks/scoring-tick'
    | '/api/public/hooks/segments-tick'
    | '/api/public/hooks/sequences-tick'
    | '/api/public/hooks/twilio-whatsapp'
    | '/api/public/hooks/twilio-whatsapp-status'
    | '/api/public/hooks/whatsapp-campaign-tick'
    | '/api/public/hooks/workflows-tick'
    | '/api/public/oauth/google-callback'
    | '/api/public/twilio/voice'
    | '/tasks/queues/$queueId/play'
    | '/api/public/booking/$slug/submit'
    | '/api/public/email/click/$messageId'
    | '/api/public/email/pixel/$messageId'
    | '/api/public/email/unsubscribe/$token'
    | '/api/public/forms/$slug/submit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/analytics'
    | '/_authenticated/communications'
    | '/_authenticated/companies'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboards'
    | '/_authenticated/deals'
    | '/_authenticated/integrations'
    | '/_authenticated/leads'
    | '/_authenticated/notes'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/tickets'
    | '/book/$slug'
    | '/portal/$token'
    | '/quote/$token'
    | '/sign/$token'
    | '/survey/$token'
    | '/_authenticated/campaigns/email'
    | '/_authenticated/campaigns/whatsapp'
    | '/_authenticated/inbox/email'
    | '/_authenticated/inbox/whatsapp'
    | '/_authenticated/integrations/$slug'
    | '/_authenticated/leads/$id'
    | '/_authenticated/leads/import-hubspot'
    | '/_authenticated/settings/audit-log'
    | '/_authenticated/settings/booking'
    | '/_authenticated/settings/calendars'
    | '/_authenticated/settings/custom-properties'
    | '/_authenticated/settings/email'
    | '/_authenticated/settings/email-templates'
    | '/_authenticated/settings/enrichment'
    | '/_authenticated/settings/esign'
    | '/_authenticated/settings/exports'
    | '/_authenticated/settings/forms'
    | '/_authenticated/settings/goals'
    | '/_authenticated/settings/macros'
    | '/_authenticated/settings/pipelines'
    | '/_authenticated/settings/playbooks'
    | '/_authenticated/settings/portal'
    | '/_authenticated/settings/products'
    | '/_authenticated/settings/quotes'
    | '/_authenticated/settings/recurring'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/rotation'
    | '/_authenticated/settings/scoring'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/segments'
    | '/_authenticated/settings/sequences'
    | '/_authenticated/settings/sla'
    | '/_authenticated/settings/subscriptions'
    | '/_authenticated/settings/surveys'
    | '/_authenticated/settings/teams'
    | '/_authenticated/settings/workflows'
    | '/_authenticated/tasks/queues'
    | '/_authenticated/integrations/'
    | '/_authenticated/settings/'
    | '/api/public/booking/$slug'
    | '/api/public/forms/$slug'
    | '/api/public/forms/embed-js'
    | '/api/public/hooks/calendar-tick'
    | '/api/public/hooks/email-broadcast-tick'
    | '/api/public/hooks/email-sync-tick'
    | '/api/public/hooks/hubspot-tick'
    | '/api/public/hooks/scheduled-exports-tick'
    | '/api/public/hooks/scoring-tick'
    | '/api/public/hooks/segments-tick'
    | '/api/public/hooks/sequences-tick'
    | '/api/public/hooks/twilio-whatsapp'
    | '/api/public/hooks/twilio-whatsapp-status'
    | '/api/public/hooks/whatsapp-campaign-tick'
    | '/api/public/hooks/workflows-tick'
    | '/api/public/oauth/google-callback'
    | '/api/public/twilio/voice'
    | '/_authenticated/tasks/queues/$queueId/play'
    | '/api/public/booking/$slug/submit'
    | '/api/public/email/click/$messageId'
    | '/api/public/email/pixel/$messageId'
    | '/api/public/email/unsubscribe/$token'
    | '/api/public/forms/$slug/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  BookSlugRoute: typeof BookSlugRoute
  PortalTokenRoute: typeof PortalTokenRoute
  QuoteTokenRoute: typeof QuoteTokenRoute
  SignTokenRoute: typeof SignTokenRoute
  SurveyTokenRoute: typeof SurveyTokenRoute
  ApiPublicBookingSlugRoute: typeof ApiPublicBookingSlugRouteWithChildren
  ApiPublicFormsSlugRoute: typeof ApiPublicFormsSlugRouteWithChildren
  ApiPublicFormsEmbedJsRoute: typeof ApiPublicFormsEmbedJsRoute
  ApiPublicHooksCalendarTickRoute: typeof ApiPublicHooksCalendarTickRoute
  ApiPublicHooksEmailBroadcastTickRoute: typeof ApiPublicHooksEmailBroadcastTickRoute
  ApiPublicHooksEmailSyncTickRoute: typeof ApiPublicHooksEmailSyncTickRoute
  ApiPublicHooksHubspotTickRoute: typeof ApiPublicHooksHubspotTickRoute
  ApiPublicHooksScheduledExportsTickRoute: typeof ApiPublicHooksScheduledExportsTickRoute
  ApiPublicHooksScoringTickRoute: typeof ApiPublicHooksScoringTickRoute
  ApiPublicHooksSegmentsTickRoute: typeof ApiPublicHooksSegmentsTickRoute
  ApiPublicHooksSequencesTickRoute: typeof ApiPublicHooksSequencesTickRoute
  ApiPublicHooksTwilioWhatsappRoute: typeof ApiPublicHooksTwilioWhatsappRoute
  ApiPublicHooksTwilioWhatsappStatusRoute: typeof ApiPublicHooksTwilioWhatsappStatusRoute
  ApiPublicHooksWhatsappCampaignTickRoute: typeof ApiPublicHooksWhatsappCampaignTickRoute
  ApiPublicHooksWorkflowsTickRoute: typeof ApiPublicHooksWorkflowsTickRoute
  ApiPublicOauthGoogleCallbackRoute: typeof ApiPublicOauthGoogleCallbackRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
  ApiPublicEmailClickMessageIdRoute: typeof ApiPublicEmailClickMessageIdRoute
  ApiPublicEmailPixelMessageIdRoute: typeof ApiPublicEmailPixelMessageIdRoute
  ApiPublicEmailUnsubscribeTokenRoute: typeof ApiPublicEmailUnsubscribeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$token': {
      id: '/survey/$token'
      path: '/survey/$token'
      fullPath: '/survey/$token'
      preLoaderRoute: typeof SurveyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$token': {
      id: '/quote/$token'
      path: '/quote/$token'
      fullPath: '/quote/$token'
      preLoaderRoute: typeof QuoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboards': {
      id: '/_authenticated/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AuthenticatedDashboardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/communications': {
      id: '/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AuthenticatedCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/integrations/': {
      id: '/_authenticated/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthenticatedIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedIntegrationsRoute
    }
    '/_authenticated/tasks/queues': {
      id: '/_authenticated/tasks/queues'
      path: '/queues'
      fullPath: '/tasks/queues'
      preLoaderRoute: typeof AuthenticatedTasksQueuesRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/settings/workflows': {
      id: '/_authenticated/settings/workflows'
      path: '/workflows'
      fullPath: '/settings/workflows'
      preLoaderRoute: typeof AuthenticatedSettingsWorkflowsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/teams': {
      id: '/_authenticated/settings/teams'
      path: '/teams'
      fullPath: '/settings/teams'
      preLoaderRoute: typeof AuthenticatedSettingsTeamsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/surveys': {
      id: '/_authenticated/settings/surveys'
      path: '/surveys'
      fullPath: '/settings/surveys'
      preLoaderRoute: typeof AuthenticatedSettingsSurveysRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/subscriptions': {
      id: '/_authenticated/settings/subscriptions'
      path: '/subscriptions'
      fullPath: '/settings/subscriptions'
      preLoaderRoute: typeof AuthenticatedSettingsSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/sla': {
      id: '/_authenticated/settings/sla'
      path: '/sla'
      fullPath: '/settings/sla'
      preLoaderRoute: typeof AuthenticatedSettingsSlaRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/sequences': {
      id: '/_authenticated/settings/sequences'
      path: '/sequences'
      fullPath: '/settings/sequences'
      preLoaderRoute: typeof AuthenticatedSettingsSequencesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/segments': {
      id: '/_authenticated/settings/segments'
      path: '/segments'
      fullPath: '/settings/segments'
      preLoaderRoute: typeof AuthenticatedSettingsSegmentsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/scoring': {
      id: '/_authenticated/settings/scoring'
      path: '/scoring'
      fullPath: '/settings/scoring'
      preLoaderRoute: typeof AuthenticatedSettingsScoringRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/rotation': {
      id: '/_authenticated/settings/rotation'
      path: '/rotation'
      fullPath: '/settings/rotation'
      preLoaderRoute: typeof AuthenticatedSettingsRotationRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/recurring': {
      id: '/_authenticated/settings/recurring'
      path: '/recurring'
      fullPath: '/settings/recurring'
      preLoaderRoute: typeof AuthenticatedSettingsRecurringRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/quotes': {
      id: '/_authenticated/settings/quotes'
      path: '/quotes'
      fullPath: '/settings/quotes'
      preLoaderRoute: typeof AuthenticatedSettingsQuotesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/products': {
      id: '/_authenticated/settings/products'
      path: '/products'
      fullPath: '/settings/products'
      preLoaderRoute: typeof AuthenticatedSettingsProductsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/portal': {
      id: '/_authenticated/settings/portal'
      path: '/portal'
      fullPath: '/settings/portal'
      preLoaderRoute: typeof AuthenticatedSettingsPortalRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/playbooks': {
      id: '/_authenticated/settings/playbooks'
      path: '/playbooks'
      fullPath: '/settings/playbooks'
      preLoaderRoute: typeof AuthenticatedSettingsPlaybooksRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/pipelines': {
      id: '/_authenticated/settings/pipelines'
      path: '/pipelines'
      fullPath: '/settings/pipelines'
      preLoaderRoute: typeof AuthenticatedSettingsPipelinesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/macros': {
      id: '/_authenticated/settings/macros'
      path: '/macros'
      fullPath: '/settings/macros'
      preLoaderRoute: typeof AuthenticatedSettingsMacrosRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/goals': {
      id: '/_authenticated/settings/goals'
      path: '/goals'
      fullPath: '/settings/goals'
      preLoaderRoute: typeof AuthenticatedSettingsGoalsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/forms': {
      id: '/_authenticated/settings/forms'
      path: '/forms'
      fullPath: '/settings/forms'
      preLoaderRoute: typeof AuthenticatedSettingsFormsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/exports': {
      id: '/_authenticated/settings/exports'
      path: '/exports'
      fullPath: '/settings/exports'
      preLoaderRoute: typeof AuthenticatedSettingsExportsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/esign': {
      id: '/_authenticated/settings/esign'
      path: '/esign'
      fullPath: '/settings/esign'
      preLoaderRoute: typeof AuthenticatedSettingsEsignRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/enrichment': {
      id: '/_authenticated/settings/enrichment'
      path: '/enrichment'
      fullPath: '/settings/enrichment'
      preLoaderRoute: typeof AuthenticatedSettingsEnrichmentRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/email-templates': {
      id: '/_authenticated/settings/email-templates'
      path: '/email-templates'
      fullPath: '/settings/email-templates'
      preLoaderRoute: typeof AuthenticatedSettingsEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/email': {
      id: '/_authenticated/settings/email'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AuthenticatedSettingsEmailRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/custom-properties': {
      id: '/_authenticated/settings/custom-properties'
      path: '/custom-properties'
      fullPath: '/settings/custom-properties'
      preLoaderRoute: typeof AuthenticatedSettingsCustomPropertiesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/calendars': {
      id: '/_authenticated/settings/calendars'
      path: '/calendars'
      fullPath: '/settings/calendars'
      preLoaderRoute: typeof AuthenticatedSettingsCalendarsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/booking': {
      id: '/_authenticated/settings/booking'
      path: '/booking'
      fullPath: '/settings/booking'
      preLoaderRoute: typeof AuthenticatedSettingsBookingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/audit-log': {
      id: '/_authenticated/settings/audit-log'
      path: '/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AuthenticatedSettingsAuditLogRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/leads/import-hubspot': {
      id: '/_authenticated/leads/import-hubspot'
      path: '/import-hubspot'
      fullPath: '/leads/import-hubspot'
      preLoaderRoute: typeof AuthenticatedLeadsImportHubspotRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/integrations/$slug': {
      id: '/_authenticated/integrations/$slug'
      path: '/$slug'
      fullPath: '/integrations/$slug'
      preLoaderRoute: typeof AuthenticatedIntegrationsSlugRouteImport
      parentRoute: typeof AuthenticatedIntegrationsRoute
    }
    '/_authenticated/inbox/whatsapp': {
      id: '/_authenticated/inbox/whatsapp'
      path: '/inbox/whatsapp'
      fullPath: '/inbox/whatsapp'
      preLoaderRoute: typeof AuthenticatedInboxWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox/email': {
      id: '/_authenticated/inbox/email'
      path: '/inbox/email'
      fullPath: '/inbox/email'
      preLoaderRoute: typeof AuthenticatedInboxEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/whatsapp': {
      id: '/_authenticated/campaigns/whatsapp'
      path: '/campaigns/whatsapp'
      fullPath: '/campaigns/whatsapp'
      preLoaderRoute: typeof AuthenticatedCampaignsWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/email': {
      id: '/_authenticated/campaigns/email'
      path: '/campaigns/email'
      fullPath: '/campaigns/email'
      preLoaderRoute: typeof AuthenticatedCampaignsEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/google-callback': {
      id: '/api/public/oauth/google-callback'
      path: '/api/public/oauth/google-callback'
      fullPath: '/api/public/oauth/google-callback'
      preLoaderRoute: typeof ApiPublicOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/workflows-tick': {
      id: '/api/public/hooks/workflows-tick'
      path: '/api/public/hooks/workflows-tick'
      fullPath: '/api/public/hooks/workflows-tick'
      preLoaderRoute: typeof ApiPublicHooksWorkflowsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-campaign-tick': {
      id: '/api/public/hooks/whatsapp-campaign-tick'
      path: '/api/public/hooks/whatsapp-campaign-tick'
      fullPath: '/api/public/hooks/whatsapp-campaign-tick'
      preLoaderRoute: typeof ApiPublicHooksWhatsappCampaignTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/twilio-whatsapp-status': {
      id: '/api/public/hooks/twilio-whatsapp-status'
      path: '/api/public/hooks/twilio-whatsapp-status'
      fullPath: '/api/public/hooks/twilio-whatsapp-status'
      preLoaderRoute: typeof ApiPublicHooksTwilioWhatsappStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/twilio-whatsapp': {
      id: '/api/public/hooks/twilio-whatsapp'
      path: '/api/public/hooks/twilio-whatsapp'
      fullPath: '/api/public/hooks/twilio-whatsapp'
      preLoaderRoute: typeof ApiPublicHooksTwilioWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sequences-tick': {
      id: '/api/public/hooks/sequences-tick'
      path: '/api/public/hooks/sequences-tick'
      fullPath: '/api/public/hooks/sequences-tick'
      preLoaderRoute: typeof ApiPublicHooksSequencesTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/segments-tick': {
      id: '/api/public/hooks/segments-tick'
      path: '/api/public/hooks/segments-tick'
      fullPath: '/api/public/hooks/segments-tick'
      preLoaderRoute: typeof ApiPublicHooksSegmentsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scoring-tick': {
      id: '/api/public/hooks/scoring-tick'
      path: '/api/public/hooks/scoring-tick'
      fullPath: '/api/public/hooks/scoring-tick'
      preLoaderRoute: typeof ApiPublicHooksScoringTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scheduled-exports-tick': {
      id: '/api/public/hooks/scheduled-exports-tick'
      path: '/api/public/hooks/scheduled-exports-tick'
      fullPath: '/api/public/hooks/scheduled-exports-tick'
      preLoaderRoute: typeof ApiPublicHooksScheduledExportsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/hubspot-tick': {
      id: '/api/public/hooks/hubspot-tick'
      path: '/api/public/hooks/hubspot-tick'
      fullPath: '/api/public/hooks/hubspot-tick'
      preLoaderRoute: typeof ApiPublicHooksHubspotTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-sync-tick': {
      id: '/api/public/hooks/email-sync-tick'
      path: '/api/public/hooks/email-sync-tick'
      fullPath: '/api/public/hooks/email-sync-tick'
      preLoaderRoute: typeof ApiPublicHooksEmailSyncTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-broadcast-tick': {
      id: '/api/public/hooks/email-broadcast-tick'
      path: '/api/public/hooks/email-broadcast-tick'
      fullPath: '/api/public/hooks/email-broadcast-tick'
      preLoaderRoute: typeof ApiPublicHooksEmailBroadcastTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/calendar-tick': {
      id: '/api/public/hooks/calendar-tick'
      path: '/api/public/hooks/calendar-tick'
      fullPath: '/api/public/hooks/calendar-tick'
      preLoaderRoute: typeof ApiPublicHooksCalendarTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/embed-js': {
      id: '/api/public/forms/embed-js'
      path: '/api/public/forms/embed-js'
      fullPath: '/api/public/forms/embed-js'
      preLoaderRoute: typeof ApiPublicFormsEmbedJsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/$slug': {
      id: '/api/public/forms/$slug'
      path: '/api/public/forms/$slug'
      fullPath: '/api/public/forms/$slug'
      preLoaderRoute: typeof ApiPublicFormsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking/$slug': {
      id: '/api/public/booking/$slug'
      path: '/api/public/booking/$slug'
      fullPath: '/api/public/booking/$slug'
      preLoaderRoute: typeof ApiPublicBookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/$slug/submit': {
      id: '/api/public/forms/$slug/submit'
      path: '/submit'
      fullPath: '/api/public/forms/$slug/submit'
      preLoaderRoute: typeof ApiPublicFormsSlugSubmitRouteImport
      parentRoute: typeof ApiPublicFormsSlugRoute
    }
    '/api/public/email/unsubscribe/$token': {
      id: '/api/public/email/unsubscribe/$token'
      path: '/api/public/email/unsubscribe/$token'
      fullPath: '/api/public/email/unsubscribe/$token'
      preLoaderRoute: typeof ApiPublicEmailUnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/pixel/$messageId': {
      id: '/api/public/email/pixel/$messageId'
      path: '/api/public/email/pixel/$messageId'
      fullPath: '/api/public/email/pixel/$messageId'
      preLoaderRoute: typeof ApiPublicEmailPixelMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/click/$messageId': {
      id: '/api/public/email/click/$messageId'
      path: '/api/public/email/click/$messageId'
      fullPath: '/api/public/email/click/$messageId'
      preLoaderRoute: typeof ApiPublicEmailClickMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking/$slug/submit': {
      id: '/api/public/booking/$slug/submit'
      path: '/submit'
      fullPath: '/api/public/booking/$slug/submit'
      preLoaderRoute: typeof ApiPublicBookingSlugSubmitRouteImport
      parentRoute: typeof ApiPublicBookingSlugRoute
    }
    '/_authenticated/tasks/queues/$queueId/play': {
      id: '/_authenticated/tasks/queues/$queueId/play'
      path: '/$queueId/play'
      fullPath: '/tasks/queues/$queueId/play'
      preLoaderRoute: typeof AuthenticatedTasksQueuesQueueIdPlayRouteImport
      parentRoute: typeof AuthenticatedTasksQueuesRoute
    }
  }
}

interface AuthenticatedIntegrationsRouteChildren {
  AuthenticatedIntegrationsSlugRoute: typeof AuthenticatedIntegrationsSlugRoute
  AuthenticatedIntegrationsIndexRoute: typeof AuthenticatedIntegrationsIndexRoute
}

const AuthenticatedIntegrationsRouteChildren: AuthenticatedIntegrationsRouteChildren =
  {
    AuthenticatedIntegrationsSlugRoute: AuthenticatedIntegrationsSlugRoute,
    AuthenticatedIntegrationsIndexRoute: AuthenticatedIntegrationsIndexRoute,
  }

const AuthenticatedIntegrationsRouteWithChildren =
  AuthenticatedIntegrationsRoute._addFileChildren(
    AuthenticatedIntegrationsRouteChildren,
  )

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedLeadsImportHubspotRoute: typeof AuthenticatedLeadsImportHubspotRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedLeadsImportHubspotRoute: AuthenticatedLeadsImportHubspotRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAuditLogRoute: typeof AuthenticatedSettingsAuditLogRoute
  AuthenticatedSettingsBookingRoute: typeof AuthenticatedSettingsBookingRoute
  AuthenticatedSettingsCalendarsRoute: typeof AuthenticatedSettingsCalendarsRoute
  AuthenticatedSettingsCustomPropertiesRoute: typeof AuthenticatedSettingsCustomPropertiesRoute
  AuthenticatedSettingsEmailRoute: typeof AuthenticatedSettingsEmailRoute
  AuthenticatedSettingsEmailTemplatesRoute: typeof AuthenticatedSettingsEmailTemplatesRoute
  AuthenticatedSettingsEnrichmentRoute: typeof AuthenticatedSettingsEnrichmentRoute
  AuthenticatedSettingsEsignRoute: typeof AuthenticatedSettingsEsignRoute
  AuthenticatedSettingsExportsRoute: typeof AuthenticatedSettingsExportsRoute
  AuthenticatedSettingsFormsRoute: typeof AuthenticatedSettingsFormsRoute
  AuthenticatedSettingsGoalsRoute: typeof AuthenticatedSettingsGoalsRoute
  AuthenticatedSettingsMacrosRoute: typeof AuthenticatedSettingsMacrosRoute
  AuthenticatedSettingsPipelinesRoute: typeof AuthenticatedSettingsPipelinesRoute
  AuthenticatedSettingsPlaybooksRoute: typeof AuthenticatedSettingsPlaybooksRoute
  AuthenticatedSettingsPortalRoute: typeof AuthenticatedSettingsPortalRoute
  AuthenticatedSettingsProductsRoute: typeof AuthenticatedSettingsProductsRoute
  AuthenticatedSettingsQuotesRoute: typeof AuthenticatedSettingsQuotesRoute
  AuthenticatedSettingsRecurringRoute: typeof AuthenticatedSettingsRecurringRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsRotationRoute: typeof AuthenticatedSettingsRotationRoute
  AuthenticatedSettingsScoringRoute: typeof AuthenticatedSettingsScoringRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsSegmentsRoute: typeof AuthenticatedSettingsSegmentsRoute
  AuthenticatedSettingsSequencesRoute: typeof AuthenticatedSettingsSequencesRoute
  AuthenticatedSettingsSlaRoute: typeof AuthenticatedSettingsSlaRoute
  AuthenticatedSettingsSubscriptionsRoute: typeof AuthenticatedSettingsSubscriptionsRoute
  AuthenticatedSettingsSurveysRoute: typeof AuthenticatedSettingsSurveysRoute
  AuthenticatedSettingsTeamsRoute: typeof AuthenticatedSettingsTeamsRoute
  AuthenticatedSettingsWorkflowsRoute: typeof AuthenticatedSettingsWorkflowsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAuditLogRoute: AuthenticatedSettingsAuditLogRoute,
  AuthenticatedSettingsBookingRoute: AuthenticatedSettingsBookingRoute,
  AuthenticatedSettingsCalendarsRoute: AuthenticatedSettingsCalendarsRoute,
  AuthenticatedSettingsCustomPropertiesRoute:
    AuthenticatedSettingsCustomPropertiesRoute,
  AuthenticatedSettingsEmailRoute: AuthenticatedSettingsEmailRoute,
  AuthenticatedSettingsEmailTemplatesRoute:
    AuthenticatedSettingsEmailTemplatesRoute,
  AuthenticatedSettingsEnrichmentRoute: AuthenticatedSettingsEnrichmentRoute,
  AuthenticatedSettingsEsignRoute: AuthenticatedSettingsEsignRoute,
  AuthenticatedSettingsExportsRoute: AuthenticatedSettingsExportsRoute,
  AuthenticatedSettingsFormsRoute: AuthenticatedSettingsFormsRoute,
  AuthenticatedSettingsGoalsRoute: AuthenticatedSettingsGoalsRoute,
  AuthenticatedSettingsMacrosRoute: AuthenticatedSettingsMacrosRoute,
  AuthenticatedSettingsPipelinesRoute: AuthenticatedSettingsPipelinesRoute,
  AuthenticatedSettingsPlaybooksRoute: AuthenticatedSettingsPlaybooksRoute,
  AuthenticatedSettingsPortalRoute: AuthenticatedSettingsPortalRoute,
  AuthenticatedSettingsProductsRoute: AuthenticatedSettingsProductsRoute,
  AuthenticatedSettingsQuotesRoute: AuthenticatedSettingsQuotesRoute,
  AuthenticatedSettingsRecurringRoute: AuthenticatedSettingsRecurringRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsRotationRoute: AuthenticatedSettingsRotationRoute,
  AuthenticatedSettingsScoringRoute: AuthenticatedSettingsScoringRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsSegmentsRoute: AuthenticatedSettingsSegmentsRoute,
  AuthenticatedSettingsSequencesRoute: AuthenticatedSettingsSequencesRoute,
  AuthenticatedSettingsSlaRoute: AuthenticatedSettingsSlaRoute,
  AuthenticatedSettingsSubscriptionsRoute:
    AuthenticatedSettingsSubscriptionsRoute,
  AuthenticatedSettingsSurveysRoute: AuthenticatedSettingsSurveysRoute,
  AuthenticatedSettingsTeamsRoute: AuthenticatedSettingsTeamsRoute,
  AuthenticatedSettingsWorkflowsRoute: AuthenticatedSettingsWorkflowsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedTasksQueuesRouteChildren {
  AuthenticatedTasksQueuesQueueIdPlayRoute: typeof AuthenticatedTasksQueuesQueueIdPlayRoute
}

const AuthenticatedTasksQueuesRouteChildren: AuthenticatedTasksQueuesRouteChildren =
  {
    AuthenticatedTasksQueuesQueueIdPlayRoute:
      AuthenticatedTasksQueuesQueueIdPlayRoute,
  }

const AuthenticatedTasksQueuesRouteWithChildren =
  AuthenticatedTasksQueuesRoute._addFileChildren(
    AuthenticatedTasksQueuesRouteChildren,
  )

interface AuthenticatedTasksRouteChildren {
  AuthenticatedTasksQueuesRoute: typeof AuthenticatedTasksQueuesRouteWithChildren
}

const AuthenticatedTasksRouteChildren: AuthenticatedTasksRouteChildren = {
  AuthenticatedTasksQueuesRoute: AuthenticatedTasksQueuesRouteWithChildren,
}

const AuthenticatedTasksRouteWithChildren =
  AuthenticatedTasksRoute._addFileChildren(AuthenticatedTasksRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCommunicationsRoute: typeof AuthenticatedCommunicationsRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDashboardsRoute: typeof AuthenticatedDashboardsRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRouteWithChildren
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRouteWithChildren
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedCampaignsEmailRoute: typeof AuthenticatedCampaignsEmailRoute
  AuthenticatedCampaignsWhatsappRoute: typeof AuthenticatedCampaignsWhatsappRoute
  AuthenticatedInboxEmailRoute: typeof AuthenticatedInboxEmailRoute
  AuthenticatedInboxWhatsappRoute: typeof AuthenticatedInboxWhatsappRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCommunicationsRoute: AuthenticatedCommunicationsRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDashboardsRoute: AuthenticatedDashboardsRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRouteWithChildren,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTasksRoute: AuthenticatedTasksRouteWithChildren,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedCampaignsEmailRoute: AuthenticatedCampaignsEmailRoute,
  AuthenticatedCampaignsWhatsappRoute: AuthenticatedCampaignsWhatsappRoute,
  AuthenticatedInboxEmailRoute: AuthenticatedInboxEmailRoute,
  AuthenticatedInboxWhatsappRoute: AuthenticatedInboxWhatsappRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicBookingSlugRouteChildren {
  ApiPublicBookingSlugSubmitRoute: typeof ApiPublicBookingSlugSubmitRoute
}

const ApiPublicBookingSlugRouteChildren: ApiPublicBookingSlugRouteChildren = {
  ApiPublicBookingSlugSubmitRoute: ApiPublicBookingSlugSubmitRoute,
}

const ApiPublicBookingSlugRouteWithChildren =
  ApiPublicBookingSlugRoute._addFileChildren(ApiPublicBookingSlugRouteChildren)

interface ApiPublicFormsSlugRouteChildren {
  ApiPublicFormsSlugSubmitRoute: typeof ApiPublicFormsSlugSubmitRoute
}

const ApiPublicFormsSlugRouteChildren: ApiPublicFormsSlugRouteChildren = {
  ApiPublicFormsSlugSubmitRoute: ApiPublicFormsSlugSubmitRoute,
}

const ApiPublicFormsSlugRouteWithChildren =
  ApiPublicFormsSlugRoute._addFileChildren(ApiPublicFormsSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  BookSlugRoute: BookSlugRoute,
  PortalTokenRoute: PortalTokenRoute,
  QuoteTokenRoute: QuoteTokenRoute,
  SignTokenRoute: SignTokenRoute,
  SurveyTokenRoute: SurveyTokenRoute,
  ApiPublicBookingSlugRoute: ApiPublicBookingSlugRouteWithChildren,
  ApiPublicFormsSlugRoute: ApiPublicFormsSlugRouteWithChildren,
  ApiPublicFormsEmbedJsRoute: ApiPublicFormsEmbedJsRoute,
  ApiPublicHooksCalendarTickRoute: ApiPublicHooksCalendarTickRoute,
  ApiPublicHooksEmailBroadcastTickRoute: ApiPublicHooksEmailBroadcastTickRoute,
  ApiPublicHooksEmailSyncTickRoute: ApiPublicHooksEmailSyncTickRoute,
  ApiPublicHooksHubspotTickRoute: ApiPublicHooksHubspotTickRoute,
  ApiPublicHooksScheduledExportsTickRoute:
    ApiPublicHooksScheduledExportsTickRoute,
  ApiPublicHooksScoringTickRoute: ApiPublicHooksScoringTickRoute,
  ApiPublicHooksSegmentsTickRoute: ApiPublicHooksSegmentsTickRoute,
  ApiPublicHooksSequencesTickRoute: ApiPublicHooksSequencesTickRoute,
  ApiPublicHooksTwilioWhatsappRoute: ApiPublicHooksTwilioWhatsappRoute,
  ApiPublicHooksTwilioWhatsappStatusRoute:
    ApiPublicHooksTwilioWhatsappStatusRoute,
  ApiPublicHooksWhatsappCampaignTickRoute:
    ApiPublicHooksWhatsappCampaignTickRoute,
  ApiPublicHooksWorkflowsTickRoute: ApiPublicHooksWorkflowsTickRoute,
  ApiPublicOauthGoogleCallbackRoute: ApiPublicOauthGoogleCallbackRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
  ApiPublicEmailClickMessageIdRoute: ApiPublicEmailClickMessageIdRoute,
  ApiPublicEmailPixelMessageIdRoute: ApiPublicEmailPixelMessageIdRoute,
  ApiPublicEmailUnsubscribeTokenRoute: ApiPublicEmailUnsubscribeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
