ALTER TABLE public.bug_reports ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.bug_reports SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_bug_reports_workspace_id ON public.bug_reports (workspace_id);
ALTER TABLE public.copilot_sessions ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.copilot_sessions SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_copilot_sessions_workspace_id ON public.copilot_sessions (workspace_id);
ALTER TABLE public.domain_events ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.domain_events SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_domain_events_workspace_id ON public.domain_events (workspace_id);
ALTER TABLE public.field_permission_rules ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.field_permission_rules SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_field_permission_rules_workspace_id ON public.field_permission_rules (workspace_id);
ALTER TABLE public.kb_articles ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.kb_articles SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_kb_articles_workspace_id ON public.kb_articles (workspace_id);
ALTER TABLE public.meet_recording_index ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.meet_recording_index SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_meet_recording_index_workspace_id ON public.meet_recording_index (workspace_id);
ALTER TABLE public.ml_forecast_scores ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.ml_forecast_scores SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_ml_forecast_scores_workspace_id ON public.ml_forecast_scores (workspace_id);
ALTER TABLE public.ml_scoring_models ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.ml_scoring_models SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_ml_scoring_models_workspace_id ON public.ml_scoring_models (workspace_id);
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.notifications SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_notifications_workspace_id ON public.notifications (workspace_id);
ALTER TABLE public.people_benefits ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.people_benefits SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_people_benefits_workspace_id ON public.people_benefits (workspace_id);
ALTER TABLE public.people_documents ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.people_documents SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_people_documents_workspace_id ON public.people_documents (workspace_id);
ALTER TABLE public.people_goals ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.people_goals SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_people_goals_workspace_id ON public.people_goals (workspace_id);
ALTER TABLE public.people_incidents ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.people_incidents SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_people_incidents_workspace_id ON public.people_incidents (workspace_id);
ALTER TABLE public.people_one_on_ones ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.people_one_on_ones SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_people_one_on_ones_workspace_id ON public.people_one_on_ones (workspace_id);
ALTER TABLE public.people_reviews ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.people_reviews SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_people_reviews_workspace_id ON public.people_reviews (workspace_id);
ALTER TABLE public.prospecting_queues ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.prospecting_queues SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_prospecting_queues_workspace_id ON public.prospecting_queues (workspace_id);
ALTER TABLE public.unipile_accounts ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.unipile_accounts SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_unipile_accounts_workspace_id ON public.unipile_accounts (workspace_id);
ALTER TABLE public.unipile_message_log ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.unipile_message_log SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_unipile_message_log_workspace_id ON public.unipile_message_log (workspace_id);
ALTER TABLE public.unipile_request_log ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.unipile_request_log SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_unipile_request_log_workspace_id ON public.unipile_request_log (workspace_id);
ALTER TABLE public.user_job_roles ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.user_job_roles SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_user_job_roles_workspace_id ON public.user_job_roles (workspace_id);
ALTER TABLE public.user_permission_sets ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.user_permission_sets SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_user_permission_sets_workspace_id ON public.user_permission_sets (workspace_id);
ALTER TABLE public.workflow_approvals ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.workflow_approvals SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_workflow_approvals_workspace_id ON public.workflow_approvals (workspace_id);
ALTER TABLE public.workflow_subscriptions ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.workflow_subscriptions SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_workflow_subscriptions_workspace_id ON public.workflow_subscriptions (workspace_id);
ALTER TABLE public.workflow_time_cursors ADD COLUMN IF NOT EXISTS workspace_id uuid;
UPDATE public.workflow_time_cursors SET workspace_id = COALESCE((SELECT w.id FROM public.workspaces w WHERE w.id = owner_id),(SELECT p.active_workspace_id FROM public.profiles p WHERE p.id = owner_id),(SELECT wm.workspace_id FROM public.workspace_members wm WHERE wm.user_id = owner_id LIMIT 1),(SELECT w2.id FROM public.workspaces w2 WHERE w2.created_by = owner_id LIMIT 1)) WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_workflow_time_cursors_workspace_id ON public.workflow_time_cursors (workspace_id);