-- Catálogo granular de permissões para cobrir 100% dos itens de menu.
WITH res(module, resource, label_pt) AS (VALUES
  ('system','branding','White-label'),
  ('system','legal_entities','Empresas (CNPJs)'),
  ('system','legal_entity_groups','Grupos empresariais'),
  ('system','language','Idioma'),
  ('system','pipelines','Pipelines'),
  ('system','custom_properties','Propriedades personalizadas'),
  ('system','custom_objects','Objetos customizados'),
  ('system','portal','Portal do cliente'),
  ('system','snippets','Snippets'),
  ('system','files','Arquivos'),
  ('system','marketplace','Marketplace'),
  ('system','widget','Widget do site'),
  ('system','import','Importações'),
  ('system','audit','Auditoria'),
  ('system','modules','Módulos'),
  ('system','integrations','Integrações'),
  ('system','whatsapp','WhatsApp'),
  ('system','linkedin','LinkedIn (Unipile)'),
  ('system','hubspot_sync','Sync HubSpot'),
  ('system','billing','Planos e cobrança'),
  ('system','members','Membros'),
  ('system','user_groups','Times'),
  ('system','roles','Permissões'),
  ('system','rbac_diagnostics','Diagnóstico de acesso'),
  ('system','settings','Configurações'),
  ('system','home','Home do workspace'),
  ('system','analytics.dashboards','Dashboards'),
  ('system','analytics.reports','Relatórios'),
  ('system','analytics.insights','Analytics'),
  ('system','automation.sequences','Sequências'),
  ('system','automation.rotation','Distribuição de leads'),
  ('system','automation.sla','SLA por etapa'),
  ('system','automation.macros','Macros'),
  ('system','automation.email_templates','Templates de email'),
  ('system','kb.articles','Base de conhecimento'),
  ('system','calendars','Calendários'),
  ('system','booking','Agendamentos'),
  ('system','onboarding_templates','Modelos de onboarding'),
  ('system','workflows','Workflows'),
  ('techsales','leads','Leads'),
  ('techsales','contacts','Contatos'),
  ('techsales','companies','Empresas'),
  ('techsales','deals','Negócios'),
  ('techsales','quotes','Cotações'),
  ('techsales','invoices','Faturas'),
  ('techsales','tickets','Tickets'),
  ('techsales','tasks','Tarefas'),
  ('techsales','task_queues','Filas de tarefas'),
  ('techsales','surveys','Pesquisas'),
  ('techsales','inbox','Inbox unificada'),
  ('techsales','inbox.email','Inbox de email'),
  ('techsales','inbox.whatsapp','Inbox de WhatsApp'),
  ('techsales','inbox.chat','Chat ao vivo'),
  ('techsales','communications','Comunicações'),
  ('techsales','notes','Notas'),
  ('techsales','meetings','Reuniões'),
  ('techsales','email_accounts','Conexão de email'),
  ('techsales','dashboard','Painel'),
  ('techsales','catalog.products','Catálogo de produtos'),
  ('techsales','catalog.services','Catálogo de serviços'),
  ('techsales','marketing.landing_pages','Landing pages'),
  ('techsales','marketing.forms','Formulários'),
  ('techsales','marketing.campaigns','Campanhas'),
  ('techsales','marketing.sdr_agent','Agente SDR'),
  ('techprojects','projects','Projetos'),
  ('techprojects','tasks','Tarefas de projeto'),
  ('techprojects','spaces','Espaços'),
  ('techprojects','timesheet','Timesheet'),
  ('techprojects','my_work','My Work'),
  ('techhire','dashboard','Dashboard do TechHire'),
  ('techhire','jobs','Vagas'),
  ('techhire','candidates','Candidatos'),
  ('techhire','pipelines','Pipelines de recrutamento'),
  ('techhire','scorecards','Scorecards'),
  ('techhire','interview_kits','Kits de entrevista'),
  ('techhire','scheduling','Agendamento de entrevistas'),
  ('techhire','sourcing.inbox','Inbox de sourcing'),
  ('techhire','sourcing.pools','Talent pools'),
  ('techhire','sourcing.sequences','Sequências de sourcing'),
  ('techhire','sourcing.referrals','Indicações'),
  ('techhire','sourcing.multi_posting','Multi-posting'),
  ('techhire','sourcing.analytics','Analytics de sourcing'),
  ('techhire','hunting','Hunting'),
  ('techhire','hunting.search','Busca de perfis'),
  ('techhire','hunting.captures','Perfis capturados'),
  ('techhire','hunting.templates','Templates de hunting'),
  ('techhire','hunting.observability','Observabilidade de hunting'),
  ('techhire','offers','Ofertas'),
  ('techhire','stage_emails','E-mails por etapa'),
  ('techhire','careers','Site de carreiras'),
  ('techhire','briefing','Briefing diário'),
  ('techhire','copilot','Recruiter Copilot'),
  ('techhire','match_scores','Match scores'),
  ('techhire','fraud_flags','Flags de risco'),
  ('techhire','notetaker','Notetaker IA'),
  ('techhire','insights','Insights ATS'),
  ('techhire','dei_analytics','DEI Analytics'),
  ('techhire','compliance','LGPD & DSAR'),
  ('techfinance','entries','Lançamentos financeiros'),
  ('techfinance','invoices','Faturas'),
  ('techfinance','payments','Pagamentos'),
  ('techfinance','recurrences','Recorrências'),
  ('techfinance','cost_centers','Centros de custo'),
  ('techfinance','banking','Integração bancária'),
  ('techfinance','bank_accounts','Contas bancárias'),
  ('techfinance','nfse','NFS-e'),
  ('techfinance','dunning','Régua de cobrança'),
  ('techfinance','charging_templates','Templates de cobrança'),
  ('techfinance','categories','Plano de contas'),
  ('techfinance','reports','Relatórios financeiros'),
  ('techfinance','legal_entities','Empresas (CNPJs)'),
  ('techfinance','legal_entity_groups','Grupos empresariais'),
  ('techfinance','audit','Auditoria financeira'),
  ('techpeople','people','Pessoas'),
  ('techpeople','my_team','Meu time'),
  ('techpeople','onboarding','Onboarding'),
  ('techpeople','offboarding','Offboarding'),
  ('techpeople','documents','Documentos'),
  ('techpeople','onboarding_templates','Modelos de onboarding'),
  ('techpeople','import','Importação de pessoas'),
  ('techpeople','wellbeing.assessments','Riscos psicossociais'),
  ('techpeople','wellbeing.incidents','Incidentes'),
  ('techpeople','incidents','Incidentes'),
  ('techpeople','benefits','Benefícios'),
  ('techpeople','timesheet','Faturamento de horas'),
  ('techpeople','allocations','Alocações'),
  ('techpeople','analytics','Analytics de pessoas'),
  ('techcontracts','contracts','Contratos'),
  ('techservice','services','Serviços'),
  ('techservice','products','Produtos')
),
acts(action, action_pt, scope, scope_pt) AS (VALUES
  ('view','Exibir','own','apenas os meus registros'),
  ('view','Exibir','team','registros da minha equipe'),
  ('view','Exibir','workspace','todos os registros'),
  ('create','Criar','own','apenas os meus registros'),
  ('create','Criar','workspace','todos os registros'),
  ('update','Editar','own','apenas os meus registros'),
  ('update','Editar','team','registros da minha equipe'),
  ('update','Editar','workspace','todos os registros'),
  ('delete','Excluir','own','apenas os meus registros'),
  ('delete','Excluir','workspace','todos os registros'),
  ('export','Exportar','workspace','todos os registros')
)
INSERT INTO public.permissions (key, module, resource, action, scope, label_pt, description, is_system)
SELECT
  r.module || '.' || r.resource || '.' || a.action || '.' || a.scope,
  r.module, r.resource, a.action::perm_action, a.scope::perm_scope,
  a.action_pt || ' ' || r.label_pt || ' (' || a.scope_pt || ')',
  NULL, true
FROM res r CROSS JOIN acts a
ON CONFLICT (key) DO NOTHING;

-- Ação "Aprovar" apenas onde faz sentido no domínio.
WITH ap(module, resource, label_pt) AS (VALUES
  ('techhire','offers','Ofertas'),
  ('techfinance','dunning','Régua de cobrança'),
  ('techfinance','invoices','Faturas'),
  ('techfinance','payments','Pagamentos'),
  ('techfinance','entries','Lançamentos financeiros'),
  ('techpeople','timesheet','Faturamento de horas'),
  ('techprojects','timesheet','Timesheet'),
  ('techsales','quotes','Cotações'),
  ('techcontracts','contracts','Contratos')
)
INSERT INTO public.permissions (key, module, resource, action, scope, label_pt, is_system)
SELECT ap.module || '.' || ap.resource || '.approve.workspace', ap.module, ap.resource,
       'approve'::perm_action, 'workspace'::perm_scope,
       'Aprovar ' || ap.label_pt || ' (todos os registros)', true
FROM ap
ON CONFLICT (key) DO NOTHING;

-- Perfis de sistema de administrador continuam com o catálogo completo.
INSERT INTO public.permission_set_items (set_id, permission_key)
SELECT ps.id, p.key
FROM public.permission_sets ps
JOIN public.permissions p ON (ps.module = 'system' OR p.module = ps.module)
WHERE ps.is_system = true
  AND (ps.name IN ('Admin','Super Admin','Workspace Admin','Workspace Owner') OR ps.name ILIKE '%Admin')
ON CONFLICT DO NOTHING;